---
title: "Joseph (Joey) Michael Hulbert"
date: "CV Updated: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    css: style.css
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

## NOTE you need to copy paste from CV document into area below table 

```

<table>
<tbody>
<tr valign="top">
<td width="450">
[Ravenholt Urban Forest Health Lab](https://treehealth.wsu.edu/),<br>
Puyallup Research and Extension Center,  
Dept. of Plant Pathology, Washington State University,  
2606 West Pioneer, Puyallup, WA, 98371-4998 USA.
</td>
<td width="442">
[https://jmhulbert.github.io](https://jmhulbert.github.io)  
1-541-908-5129  
[hulbe@wsu.edu](mailto:hulbe@wsu.edu)  
[Curriculum Vitae PDF](https://jmhulbert.github.io/JMH-CV-PDFv2.pdf)
</td>
</tr>
</tbody>
</table>


## Academic Appointments

+ 2024-2025. **Career Track Assistant Research Professor**, Department of Plant Pathology, Washington State University.
+ 2022-2024. **Postdoctoral Research Associate**, WSU Puyallup Research and Extension Center, Washington State University.
+ 2020-2022. **USDA NIFA Postdoctoral Fellow**, Ornamental Plant Pathology, WSU Puyallup Research and Extension Center, Washington State University.

## Education

+ 2015-2020. **PhD** Plant Pathology, Forestry and Agricultural Biotechnology Institute, Dept. of Plant & Soil Science, University of Pretoria, South Africa. Dissertation: _Phytophthora_ diversity in the Cape Floristic Region. Primary Supervisor: Mike Wingfield. Co-Supervisors: Treena Burgess, Francois Roets.
+ 2016-2019. **Affiliate Research Student**, Dept. of Conservation Ecology & Entomology, Stellenbosch University, South Africa.
+ 2012-2014. **Dual MSc** Dept. of Botany & Plant Pathology, Dept. of Wood Science & Engineering, Oregon State University. Thesis: Phytosanitation of Douglas-fir (_Pseudotsuga menziesii_) logs to mitigate the risk of artificially disseminating _Phytophthora ramorum_ within the global trade of timber. Advisers: Everett Hansen & Jeff Morrell.
+ 2006-2010. **BSc** Dept. of Natural Resource Sciences, Washington State University. Undergraduate Thesis: Influence of climatic variables on forest growth in the Sierra Nevada Mountains.

## Initiatives

+ 2024- PI, _Equitable Urban Forest Internship Program_ ([https://treehealth.wsu.edu/internship](https://treehealth.wsu.edu/internship)), Washington State University, USDA Forest Service Inflation Reduction Act Urban and Community Forestry Grant. 
+ 2024- PI _Western Redcedar Parks Study (long term tree monitoring program)_ [iNaturalist Project](https://www.inaturalist.org/projects/western-redcedar-parks-study), Washington State University and MetroParks Tacoma.
+ 2022- PI, _Ravenholt Urban Forest Health Lab_ ([https://treehealth.wsu.edu/](https://treehealth.wsu.edu/)), Washington State University, Albert Victor Ravenholt Fund. 
+ 2020- Program Director, _Forest Health Watch_ ([https://foresthealth.org/](https://foresthealth.org/)), Washington State University, United States Department of Agriculture, National Institute of Food and Agriculture.
+ 2022- Project Director, _USDA APHIS PPA 7721 Invasive Species Outreach for Tribes_ ([https://extension.wsu.edu/invasive-species](https://extension.wsu.edu/invasive-species)), Washington State University.
+ 2020- Organizer, _WSU Forestry Working Group_, Washington State University.
+ 2020- Organizer, _Pacific Northwest Citizen Science Network_ [https://pnwcitsci.org/](https://pnwcitsci.org)
+ 2016-2020 Project leader, _Cape Citizen Science_ ([https://citsci.co.za/](https://citsci.co.za/)), Forestry and Agricultural Biotechnology Institute, University of Pretoria, Stellenbosch University, DST-NRF Centre of Excellence in Tree Health Biotechnology.
+ 2019- Organizer, _Forest Health Citizen Science Community_ ([https://fhcs.page/](https://fhcs.page)).
+ 2018-2019 Instructor, _R for biology and ecology workshop series_ ([https://jmhulbert.github.io/r/](https://jmhulbert.github.io/r/)), two series offered at University of Pretoria and one series offered at Stellenbosch University.
+ 2012-2014 Co-founder, _Inspiration Dissemination_ ([http://blogs.oregonstate.edu/inspiration/](http://blogs.oregonstate.edu/inspiration/)), KBVR 88.7fm, Oregon State University.

## Community Service

+ 2024- Core Member, City of Tacoma, Forest and Cities Network.
+ 2024 Urban Forest Management Plan Advisory Council, MetroParks Tacoma. 
+ 2021-2027 Volunteer, Nature and Environment Council, MetroParks Tacoma.
+ 2021  Member, Pierce County Community Engagement Task Force.
+ 2021  Volunteer Mechanic, Second Cycle, Tacoma, Washington.
+ 2020-2021 Voting Member, Puyallup Watershed Initiative, Forest Community of Interest.
+ 2018  Volunteer Mechanic, Palouse Bicycle Collective, Moscow, Idaho.
+ 2014-2015 Volunteer Shop Manager, Corvallis Bicycle Collective, Corvallis, Oregon.

## Publications 
### Book Chapters
  + Liebhold A, Moltzen B, Juzwik J, **Hulbert JM**, (submitted) Forest tree pathogen biosecurity. USFS National Forest Health Assessment Chapter 6.
  + Van der Colff D, Ebrahim I, Powrie LW, Rebelo AG, Edge D, Mecenero S, Scott SL, Hoffman MT, **Hulbert JM**, Ditlhale N, Mahood K, Gafen M, Sink KJ, Franken M, Zikishe V, Grieve K, Parbhoo S, Dayaram A and Turner SC. 2019\. ‘Biodiversity provides opportunities for citizen science’ chapter in _National Biodiversity Assessment 2018: Compendium of Benefits of Biodiversity_. South African National Biodiversity Institute, Pretoria. hdl.handle.net/20.500.12143/6491

### Peer-Reviewed Manuscripts
  + Andrus et al. 2024. [Canary in the Forest? – Tree mortality and canopy dieback of western redcedar linked to drier and warmer summers](https://onlinelibrary.wiley.com/doi/epdf/10.1111/jbi.14732). _Journal of Biogeography_ JBI-23-0212.R1.
  + Brooks R, Omdall D, **Hulbert JM**, Brown S, Marshall JC, Elliott M, Chastagner GA. 2023. [_Cryptostroma corticale_, the causal agent of sooty bark disease of maple, appears widespread in western Washington State](https://onlinelibrary.wiley.com/doi/10.1111/efp.12835), USA. _Forest Pathology_. Online Early View e12835.
  + **Hulbert JM**, Hallett RA, Roy HE, Cleary M 2023. [Citizen science can enhance strategies to detect and manage invasive forest pests and pathogens](https://www.frontiersin.org/articles/10.3389/fevo.2023.1113978/full), _Frontiers in Ecology and Evolution_ 11. DOI: 10.3389/fevo.2023.1113978.
  + Lanning KK, Kline N, Elliott M, Stamm E, Warnick T, LeBoldus JM, Garbelotto M, Chastagner GA, **Hulbert JM** 2023. [Citizen science can add value to *Phytophthora* monitoring: five case studies from western North America](https://www.frontiersin.org/articles/10.3389/fenvs.2023.1130210/full). _Frontiers in Environmental Science_ 11. DOI: 10.3389/fenvs.2023.1130210.
  + Fraisl D, Hager G, Bedessem B, Hsing P, Gold M, Haklay M, **Hulbert, JM**, and others 2022. [Citizen Science in environmental and ecological sciences](https://www.nature.com/articles/s43586-022-00144-4), _Nature Review Methods Primers_ 2, 64. DOI: 10.1038/s43586-022-00144-4.
  + Engelbrecht J, Duong TA, Paap T, **Hulbert JM**, Hanneman JJ, van den Berg N 2022 \. [Population genetic analyses of *Phytophthora cinnamomi* reveals three lineages and movement between natural vegetation and avocado orchards in South Africa](https://pubmed.ncbi.nlm.nih.gov/35037471/). _Phytopathology_. DOI: 10.1094/PHYTO-10-21-0414-R
  + Bose TB, **Hulbert JM**, Burgess TI, Paap T, Wingfield MJ 2021\. [Two novel *Phytophthora* species from the Cape Floristic Region of South Africa](https://link.springer.com/article/10.1007/s11557-021-01702-y). _Mycological Progress_, 20(6):755-767\. DOI: 10.1007/s11557-021-01702-y.
  + Elliott M, **Hulbert JM**, Streng D, Chastagner GA 2021\.  [Multiagency collaborations help public gardens contain *Phytophthora* outbreaks while providing insights and opportunities for novel research](https://apsjournals.apsnet.org/doi/10.1094/PHP-02-21-0045-FI). _Plant Health Progress_. DOI: 10.1094/PHP-02-21-0045-FI.
  + Paap T, Wingfield MJ, Burgess I, **Hulbert JM**, Santini A. 2020\. [Harmonising the fields of invasion science and forest pathology](https://neobiota.pensoft.net/article/52991/). _NeoBiota_ 62:301-332. DOI: 10.3897/neobiota.62.52991.
  + **Hulbert JM**, Paap T, Burgess TI, Roets F, Wingfield MJ. 2019\. [Botanical gardens provide valuable baseline _Phytophthora_ diversity data](https://www.sciencedirect.com/science/article/abs/pii/S1618866719304091). _Urban Forestry and Urban Greening_ 46:126461\. DOI: 10.1016/j.ufug.2019.126461\.
  + Ryan SF and 41 others, 2018\. [The role of citizen science in addressing grand challenges in food and agriculture research](https://royalsocietypublishing.org/doi/10.1098/rspb.2018.1977), _Proceedings of the Royal Society B_ 285(1891)\. DOI: 710.1098/rspb.2018.1977.
  + **Hulbert JM**, Agne MC, Burgess TI, Roets F, Wingfield MJ. 2017\. [Urban environments provide opportunities for early detection of _Phytophthora_ invasions](https://link.springer.com/article/10.1007/s10530-017-1585-z), _Biological Invasions_ 19:3629–3644\. DOI: 10.1007/s10530-017-1585-z.
  + Peterson E, Hansen EM, **Hulbert JM**. 2014\. [Source or Sink? The role of soil and water borne inoculum in the dispersal of _Phytophthora ramorum_ in Oregon tanoak forests](https://www.sciencedirect.com/science/article/abs/pii/S0378112714001261). _Forest Ecology and Management_, 322:48-57\. DOI: 10.1016/j.foreco.2014.02.031. 
 
### Not Peer-Reviewed Manuscripts

  + Hester SN, Kruger H, Ticehurst JL, **Hulbert JM** and Cacho OJ. 2023. [Editorial: The Role of Community and Industry Surveillance in Managing Invasive Species: A Review of Current Knowledge](https://www.frontiersin.org/articles/10.3389/fevo.2023.1281472/full). _Frontiers in Ecology and Evolution_ 11. (accepted).
  + Elliott M, Rollins L, Bourret T, **Hulbert JM**, Chastagner GA 2021\. [Three new hosts for _Phytophthora ramorum_ confirmed in Washington State: Salal, Oregon grape, and red huckleberry](https://apsjournals.apsnet.org/doi/10.1094/PHP-01-21-0003-FI), _Plant Health Progress_. DOI: 10.1094/PHP-01-21-0003-FI.
  + Chastagner GA, Elliott M, **Hulbert JM** 2021\. Effectiveness of fungicides and biopesticides in controlling Botrytis gray mold on western hemlock nursery stock. _Tree Planter's Notes_, 64(1):21-31.
  + **Hulbert JM**, Turner SC, Scott SL. 2019\. [Challenges and solutions to establishing and sustaining citizen science projects in South Africa](https://journals.co.za/doi/pdf/10.17159/sajs.2019/5844), _South African Journal of Science_, 115(7/8). DOI: 10.17159/sajs.2019/5844.
  + Auerbach J, Barthelmess E, Cavalier D, Cooper C,Fenyk H, Haklay M, **Hulbert JM**, Kyba C, Larson L, Lewandowski E, Shanley L. 2019\. [The problem with delineating narrow criteria for citizen science](https://www.pnas.org/doi/10.1073/pnas.1909278116). _Proceedings of the National Academy of Sciences_, 116(31). DOI: 10.1073/pnas.1909278116.
  + **Hulbert JM** 2019\. Citizen science increases the ethics of foreign led research, _Narrative Inquiry in Bioethics_, Johns Hopkins University Press. Volume 9, Number 1, Spring 2019\. DOI: 10.1353/nib.2019.0024.
  + **Hulbert JM**, Roets F. 2018\. [Science engagement in South Africa](https://www.science.org/doi/10.1126/science.aav1499). _Science_, 361(6406):985\. DOI: 10.1126/science.aav1499.
  + **Hulbert JM**. 2016\. [Citizen science tools available for ecological research in South Africa](https://journals.co.za/doi/pdf/10.17159/sajs.2016/a0152), _South African Journal of Science_, 112:5/6\. DOI: 10.17159/sajs.2016/a0152.

### Manuscripts in Review or Revision

  + **Hulbert JM** (submitted). More mentorship needed for research co-production with marginalized communities.
  + **Hulbert JM**, Roets F, Burgess TI, Wingfield MJ. (under revision). Exotic and putatively native _Phytophthora_ species are associated with distinct plant communities in southern Afrotemperate Forests.
  + Louw NL, Roets F, **Hulbert JM** (under revision). Molecular techniques reveal additional factors in the decline of the endangered silver tree (_Leucadendron argenteum_).
  + **Hulbert JM**, Scholtz K, Roets F. (under revision). Youth participation in citizen science reveals differences between outreach and engagement and connects plant pathology research to public health.
  
### Manuscripts in Prep

  + **Hulbert JM** and others (in prep). Western redcedar dieback increases with urban heat. 
  + **Hulbert JM**, Elliott M, McNees T, Chastagner G (in prep). Stakeholder engagement increases knowledge of distribution and host range of _Cryptostroma corticale_.
    + **Hulbert JM** and others (in prep). Community science reveals important environmental factors associated with western redcedar dieback. 


### Extension Fact Sheets
 
  + Dewitz F, Darr M, Murray T, Zobrist K, Kohler G, **Hulbert J**. In Prep. Bronze Birch Borer. 
  + Dewitz F, Darr M, Murray T, Zobrist K, Kohler G, **Hulbert J** (submitted). Mediterranean Oak Borer. 
 + Zobrist KW, Bomberger RA, Glass J, **Hulbert JM**, Darr M, Roberts E. 2023. [Managing emerald ash borer in Washington State](https://pubs.extension.wsu.edu/managing-emerald-ash-borer-in-washington-state), WSU Extension Fact Sheet FS384.
  + Zobrist KW, Bomberger RA, Glass J, Marquis J, **Hulbert JM**, Darr M, Roberts E, (accepted). [Emerald Ash Borer and its implications for Washington State](https://pubs.extension.wsu.edu/emerald-ash-borer-and-its-implications-for-washington-state), WSU Extension Manual EM127.
  + Brooks R, **Hulbert JM**, Omdall D, Elliott M, Chastagner GA 2022. [Sooty Bark Disease Diagnostic Guide](https://pubs.extension.wsu.edu/sooty-bark-disease-diagnostic-guide), WSU Extension Fact Sheet FS375E.

### ArcGIS Story Maps
 
  + **Hulbert JM** Avila N, Nicholson M, Bridges C, Schreiber B, Agne M, Dewitz F. (External Review). [Western redcedar and urban heat in Portland, Oregon.](https://storymaps.arcgis.com/
  + Dewitz F, **Hulbert JM**. 2023. [Tacoma schools, urban heat and trees](https://storymaps.arcgis.com/stories/0b8e2570da4a47d3a6ffb0907b738cea)
  + **Hulbert JM**, Elliott JM, Chastagner G. 2023. [*Phytophthora* communities in eastern Cascade waterways](https://storymaps.arcgis.com/stories/af79904ceee04d019c8db5699819aaea)

### Community Science Field Guides

  + Dewitz F, **Hulbert JM**. 2024. [Sword Fern Soil Sample Collection Guide](https://foresthealth.org/wp-content/uploads/2024/08/Sword-Fern-Field-Sampling-Protocolv2.pdf)
  + Dewitz F, **Hulbert JM**. 2023. [Maple Health Watch Research - iNaturalist and Sample Collection Field Manual](https://foresthealth.org/wp-content/uploads/2023/05/Maple-Health-Watch-Maple-Health-Watch.pdf).
  + **Hulbert JM** 2022. [Soil Sample Collection Guide](https://foresthealth.org/wp-content/uploads/2023/01/Soil-Sample-Collection-Guide.pdf).
  + **Hulbert JM**, Dewitz F. 2022. [Tacoma Street Tree Vulnerability Study iNaturalist - Field Manual](https://foresthealth.org/wp-content/uploads/2022/11/Tacoma-Street-Tree-Vulnerability-Study-Guide-1.pdf). 
  + Evans A, **Hulbert JM**. 2022. [Western Redcedar Dieback Project - iNaturalist Field Manual 3.0](https://foresthealth.org/wp-content/uploads/2022/10/Redcedar-Dieback-iNaturalist-Field-Guide-v3.pdf).
  
### Program Progress Reports

+ **Hulbert JM**. 2023. [_Ravenholt Urban Forest Health Lab Progress Report_](https://s3.wp.wsu.edu/uploads/sites/3191/2023/09/Ravenholt-Progress-Report-2023-v4.pdf). 

## Funding and Support

### Totals

**Total Funding Secured as Postdoc (2020- )**

+ Funding awarded at WSU:	**$3,454,790**
+ Funding awarded as PI: **$3,018,654**
+ Funding pending: **$98,823**
+ Funding applied for at WSU: **5,385,082**

### Postdoc Fellowship Proposals

#### Funded

+ 2020-2022 **PD**, _Forest Health Defenders: enhancing biosecurity through public engagement in plant disease research_. USDA NIFA EWD Postdoctoral Research Fellowship program **($164,967)**. 

#### Submitted

+ 2022-2023 **PI**, _Visualizing western redcedar vulnerability and demonstrating assisted seed migration as an approach for climate adaptation_. USGS Northwest Climate Adaptation Science Center Research Fellowship Program **($65,069)**.
+ 2020-2021 **PI**, _Developing a toolkit for climate adaptive conservation of the western redcedar in the Pacific Northwest_. USGS Northwest Climate Adaptation Science Center Research Fellowship Program **($63,383). Application withdrawn to accept above**. 
+ 2020-2022 **PI**, _Surveying Phytophthora diversity in the Olympic National Forest with citizen science_. NSF Postdoctoral Fellowship in Biology, Broadening Participation of Groups Under-represented in Biology **($138,000). Application withdrawn to accept above**. 
+ 2020 **Postdoc**, _Forest Health Defenders: public engagement to conserve the western redcedar_. David H. Smith Conservation Research Fellowship, Society for Conservation Biology **($123,000)**. 
+ 2019 **Postdoc**, _Moss, metals and microbes: revealing hotspots of stormwater contamination with citizen science in the Puget Sound_. David H. Smith Conservation Research Fellowship, Society for Conservation Biology **($178,710)**. 

### Research Grants

#### Funded

+ 2024 **Co-PI**, _Navigating new challenges: drought and sooty bark disease in the northwest_. Washington State Department of Natural Resources **($100,000)**.
+ 2024 **PI**, _Tacoma Volunteer Tree Inventory Program_. Washington State Department of Natural Resources Community Forestry Assitance Grant **($348,369)**.
+ 2023 **PI**, _Enriching Tribal management and resilience to invasive species with co-designed educational materials_. USDA APHIS PPQ PPA Section 7721 **($88,221)**.
+ 2023 **PI**, _Empowering community college students to equitably enhance urban forests_. USDA Forest Service, Urban and Community Forestry, Inflation Reduction Act **($1,786,431)**.
+ 2023 **PI**, _Enhancing bio-surveillance in the Pacific Northwest by strengthening and leveraging the networks of the Forest Health Watch_. USDA Forest Service, Bipartisan Infrastructure Law **($145,000)**.
+ 2023 **PI**, _Increasing Native Vigilance, Awareness and Surveillance of Invasions via Education and Resources (INVASIVE-R) Project (Year Two)_. USDA APHIS PPQ PPA Section 7721 **($89,403)**.
+ 2023 **Co-PI**, _Washington Nursery and Landscape Biosurveillance Education Program_. Washington State Department of Agriculture, Nursery Research Funding **($15,000)**.
+ 2022 **PI**, _Detecting biological invasions with sentinel plantings at ports and urban points of dispersal in Washington State_. USDA Forest Service, International Programs **($205,071)**
+ 2022 **PI**, _Tacoma Sooty Bark Disease Vulnerability_. Washington State Department of Natural Resources, Community Forestry Assistance Grant **($40,000)**.
+ 2022 **PI**, _Increasing Native Vigilance, Awareness and Surveillance of Invasions via Education (INVASIVE) Project_. USDA APHIS PPQ PPA Section 7721 **($77,763)**.
+ 2021 **Co-PI**, _Survey and diagnostic activities to identify distribution and host range for maple sooty bark disease in urban areas of the Puget Sound region_. USDA Forest Service Emerging Pests program **($31,750)**.
+ 2020 **Co-PI**, _Stream survey of Phytophthora spp. present in Pacific Northwest larch forests considered to be high risk for P. ramorum_ establishment_. USDA Forest Service Emerging Pests program **($35,910)**. 
+ 2020 **Cooperator/Proposal Author**, _Lateral movement of Phytophthora ramorum in nursery substrates_. USDA APHIS PPQ PPA Section 7721 **($48,582)**. 

#### Pending

+ 2024 **PI**, _Enhancing Tribal resilience to invasive species with co-designed educational materials_. USDA APHIS PPQ PPA Section 7721. **($88,253)**.
+ 2024 **Co-PI**, _Agriculture Biosecurity: Enhancing Biosecurity by Linking Invasive Species Models with Community Science_. USDA AFRI Foundational Grants **($649,002)**.
+ 2024 **Co-PI**, _Enhancing Capacity Among Northwest Tribes and Extension to Promote Climate-Smart Forestry_. USDA AFRI Foundational Grants (pass-through).  **($155,000)**.
+ 2024 **PI**, _Forest Health Watch first detector program_. USDA APHIS PPQ PPA Section 7721. **($86,080)**.
+ 2024 **PI**, _Safeguarding Tribal plant nurseries with educational activities and resources_. USDA APHIS PPQ PPA Section 7721. **($112,483)**.
+ 2023 **Co-PI**, _Early detection and monitoring of C. corticale with spore trapping and qPCR_. USDA Forest Service Special Technology Development Program **($83,823)**.

#### Submitted

+ 2024 **PI**, _Leveraging the Forest Health Watch network to pilot a seed collection program for conserving western redcedar_ USDA Forest Service Participatory Sciences Grant **($19,912)**.
+ 2023 **PI**, _Engaging community college students in tree inventory and monitoring blitzes in Washington State _. USDA Forest Service, Bipartisan Infrastructure Law **($285,000)**.
+ 2023 **PI**, _Washington Statewide Campus Tree Blitz_ **($40,000)**.
+ 2022 **Co-PI**, _Schools as oases in urban heat islands: addressing urban forest equity through school and community partnerships and research_. National Science Foundation, Civic Innovation Challenge **($48,653)**.
+ 2021 **PI**, _Community engagement to explore the microbes associated with the dieback of western redcedar_. USGS Directed Research Funding - Northwest Climate Adaptation Science Center **($226,493)**.
+ 2021 **PI**, _Empowering communities to understand the effects of climate change on forest health, accelerate research about the dieback of western redcedar, and recognize genetic diversity as a tool for increasing climate resiliency_. USDA Forest Service Urban & Community Forestry 2021 Challenge Cost Share Grant Program **($299,539)**.
+ 2020 **Co-PI/Postdoc**, _Seattle Urban Forest Atlas: An interactive citizen-science geo-database and simulation platform to promote healthy, resilient, and equitable urban forests_. University of Washington EarthLab Innovation Grants Program **($74,141)**. 
+ 2019 **PI**, _Forest Health Defenders: Public engagement to conserve the western redcedar_. USDA Forest Service Citizen Science Competitive Funding Program Application **($30,000)**.  

### Foundation Grants and Gifts

#### Funded

+ 2022 **PI**, _Ravenholt Urban Forest Health Lab_, Albert Victor Ravenholt Fund **($270,000)**.

#### Pending

+ 2024 **Co-PI**, _Engaging Tribal, Conservation District, NGO, and Local Government Entities on Plant Holding Facilities Management_. Bonneville Environmental Foundation (pass-through). **($29,194)**
+ 2024 **PI**, _Enhancing Urban Forest Planning and Practices in the Pacific Northwest with Online Activities and Resources_ Frank & Evelyn Schmidt Family Foundation **(40,000)**.
+ 2024 **PI**, _Enhancing the Impact and Capacity of WSU’s Outreach Activities with New Technologies_ Bamford Foundation **($15,000)**

#### Submitted

+ 2024 **PI**, _Mediterranean Oak Borer surveillance and trapping with community science_ Sustainable Path Foundation **($15,000)**
+ 2024 **PI**, _Washington State University - Forest Health Watch Mobile Science Laboratory_ Ben B. Cheney Foundation **($100,000)**
+ 2024 **PI**, _Placing next-generation sequencing tools in the hands of disadvantaged youth_ Extension Foundation **($20,000)**
+ 2023 **PI**, _Bamford Foundation Urban Science Internship Program_ Bamford Foundation **($270,000)**.
+ 2022 **PI**, _Minimizing Human Health Risks and Urban Tree Infections from Sooty Bark Disease_, Tree Research and Education Endowment Fund, John Z. Duling Grant **($24,942)**.
+ 2022 **Co-PI**, _Co-Developing Tree Planting Guides for Cities: A Case Study in Tacoma Washington_, Frank & Evelyn Schmidt Family Foundation **($25,000)**.


### Funded Outreach Grants

+ 2020 Tribal Engagement Activity Proposal, Forest Community of Interest, Puyallup Watershed Initiative **($8,500)**.
+ 2018 Social Impact Grant, Faculty of AgriScience, Stellenbosch University **(~$4,000, received in ZAR)**.
+ 2017 Mathre Education Endowment Award, American Phytopathological Society **($1,000)**.
+ 2017 Plant Pathology Promotion Fund, British Society for Plant Pathology **(~$2,500, received in ZAR)**.

### Crowdfunded Projects

+ 2017 Engage Kayamandi Youth in Cape Citizen Science with Vision Afrika, [DOI:10.18258/8690](https://experiment.com/projects/engage-kayamandi-youth-in-cape-citizen-science-with-vision-afrika) **($626)**.
+ 2015 Discovering Plant Destroyers in South Africa with Citizen Science, [DOI:10.18258/2066](https://experiment.com/projects/discovering-plant-destroyers-in-south-africa-with-citizen-science) **($5,000)**. 

### In Kind Donations

+ 2021 Field Sampling Equipment (GPS units, camera traps, communication devices), Transition Fidalgo
+ 2021 Field Notebooks, Rite in the Rain
+ 2021 Western redcedar trees, Weyerhaeuser
+ 2021 Soil temperature and moisture monitoring equipment, Meter
+ 2017 Field Guide to Fynbos (20 copies), Rapula Trust


### Sponsored Internship Proposals

+ 2023 _Keeping trees healthy in urbanizing environments of the Pacific Northwest_ College of Agriculture, Human and Natural Resource Sciences, Washington State University **($2,000)**.
+ 2022 _Supporting ornamental, flower, and bulb crop productions in the Pacific Northwest through applied research_, College of Agriculture, Human and Natural Resource Sciences, Washington State University, Research and Extension Experiences for Undergraduates (REEU): Sustainable High-value Horticulture and Processing **($4,500)**.
+ 2022 _Keeping trees healthy in changing environments of the Pacific Northwest_, College of Agriculture, Human and Natural Resource Sciences, Washington State University **($3,000)**.
+ 2021 _Tree health and heat islands in Seattle_, College of the Environment, Environmental Science, University of Washington, Capstone Project Proposal.

## Academic Honors & Awards

+ 2024 Travel Award, Department of Plant Pathology
+ 2024 Bronze Award for long publication, (*EAB and its implications in Washington State*), Association of Natural Resource Extension Professionals 
+ 2019 Getting the Message to the Public, Forestry and Agricultural Biotechnology Institute
+ 2018 Travel Fund, British Society for Plant Pathology
+ 2018 Stephen A. Johnston Student Travel Award, American Phytopathological Society
+ 2016 Getting the Message to the Public, Forestry and Agricultural Biotechnology Institute
+ 2016 Best Student Personal Website, Forestry and Agricultural Biotechnology Institute
+ 2015 Best PhD Oral Presentation, Dept. of Plant Science Postgraduate Research Symposium
+ 2014 Graduate Scholarship, Oregon Lottery
+ 2014 Travel Award, Oregon State University Graduate School
+ 2014 Student Travel Award, Botany and Plant Pathology Graduate Student Association
+ 2014 Bartholomew Memorial Scholarship
+ 2014 Most Innovative Radio Program, Intercollegiate Broadcasting System
+ 2014 Best WSE Oral Presentation, Western Forestry Graduate Research Symposium
+ 2013 Schutz Family Fellowship
+ 2013 Alfred W. Moltke Fellowship
+ 2013 Jack & Lila Saubert Fellowship
+ 2013 Larry Moore Award for Graduate Education in Plant Pathology
+ 2013 Student Travel Award, Western International Forest Disease Work Conference

## Academic Leadership

+ 2022- Vision Committee Member, WSU Puyallup Research and Extension Center 
+ 2020- Program Director, Forest Health Watch
+ 2020- Organizer, Forestry Working Group, Washington State University
+ 2021- Member, Forest Adaptation Network
+ 2017-2020 Committee Member, American Phytopathological Society, Committee for Diversity and Equality
+ 2017-2020 Committee Member, American Phytopathological Society, Forest Pathology Committee
+ 2016-2020 Founder and Project Leader, Cape Citizen Science
+ 2015 Coordinator, University of Pretoria Invasive Species Journal Club
+ 2014 Founder and Director, Botany and Plant Pathology BUDS Program
+ 2014 Planning Committee Member, Western Forestry Graduate Research Symposium
+ 2013-2014 President, Botany and Plant Pathology Graduate Student Association
+ 2013-2014 Co-Founder and Director, Forest Graduate Undergraduate Mentorship Program
+ 2013 Planning Committee Member, Western Forestry Graduate Research Symposium
+ 2013 Planning Committee Member, College of Forestry Graduate Student Orientation
+ 2013 Organizer, Natural Science Graduate Student BBQ
+ 2012-2014 Co-host, Inspiration Dissemination
+ 2012-2014 Officer, College of Forestry Graduate Student Council
+ 2012-2014 Wood Science Steward, Coalition of Graduate Employees
+ 2012-2014 Graduate Representative, Dept. of Wood Science and Engineering
+ 2012-2014 Committee Member, Wood Science and Engineering Graduate Affairs
+ 2012 Organizer, Natural Science Graduate Student BBQ

## Teaching Experience

### Guest Lectures

+ 2024 Pacific University, Plant Pathology Lecture, _Forest health - issues, research and student opportunities._
+ 2023 Washington State University, Department of Plant Pathology, General Plant Pathology (PLP 429) Lecture, _Forest Pathology - tree health issues in the Pacific Northwest._
+ 2023 Washington State University, School of the Environment, Disturbance Ecology (SOE 485) Lecture, _Forest Pathology in the Pacific Northwest._
+ 2023 Highline Community College, Botany and Evolution, _Urban forests, tree health, equity and community science_ (two lectures).
+ 2023 Pacific University, Plant Pathology Lecture, _Western redcedar dieback and research and student opportunities._
+ 2023 University of Puget Sound, Research Methods, _Tacoma community science, western redcedar health as indicators of inequities_.
+ 2023 Green River College, Forest Ecology, On-Campus Lab instruction, _Western redcedar dieback on Green River Campus._
+ 2023 University of Washington Tacoma, Environmental Science, _Urban forest health and community science in Tacoma_.
+ 2022 Washington State University, Plant Pathology (PLP 429) _Forest Pathology - Tree health issues in the Pacific Northwest_.
+ 2022 Pierce College, Cell Biology, _Stream sampling for Phytophthora_ (2 classes, two field lessons and one lab visit).
+ 2022 University of Washington, Human Centered Design and Engineering, Directed Research Groups, Spring Quarter, _The UX of climate change: western redcedar dieback._ 
+ 2022 Green River College, Forest Resource Management, Forest Ecology, On-Campus Lab instruction, _Western redcedar dieback and Sooty Bark Disease issues on Green River Campus._
+ 2022 Washington State University, School of the Environment, Graduate class in Ecology (SOE 593) Lecture, _Western redcedar dieback and the community science approach._
+ 2021 Washington State University, Department of Plant Pathology, General Plant Pathology (PLP 429) Lecture, _Forest Pathology - concepts and issues in the Pacific Northwest._
+ 2021 Pierce College, Cell Biology, On-Campus Lecture, _The need for more forest health scientists to increase climate resilience in urban communities._
+ 2021 Green River College, Forest Resource Management, Forest Health and Protection course, On-Campus Lab instruction, _Sooty bark disease and western redcedar dieback on Green River campus._
+ 2021 Pacific University, Department of Biology and Environmental Science, Plant Pathology, _Western redcedar dieback - plant pathology research with Pacific University._
+ 2021 Evergreen State College, Environmental Studies, Field Ecology Lecture, _Western redcedar dieback - exploring local project opportunities with students at Evergreen State College._
+ 2021 Green River College, Forest Resource Management, Forest Ecology Lecture, _Western redcedar dieback - exploring local project opportunities with students at Green River College._
+ 2021 Washington State University, School of the Environment, Disturbance Ecology (SOE 485) Lecture, _Tree root diseases - effects at multiple scales._
+ 2021 University of Washington, Human Centered Design and Engineering, Directed Research Group, Winter & Spring Quarters, The UX of climate change: _Forest Health Watch - community engagement for healthy forests_
+ 2020 Washington State University, Department of Plant Pathology, General Plant Pathology (PLP 429) Lecture, _Forest Pathology._
+ 2020 Washington State University, 4H Ecostewards Program, Chelan/Douglas County Extension, Guest Lecture, _Super Fungi - adaptations and super powers._
+ 2018 Cape Peninsula University of Technology, Faculty of Applied Sciences, Btech Plants Module, Lecture, _Invasive microscopic organisms: plant pathogens and biosecurity._
+ 2018 Stellenbosch University, Dept. of Conservation Ecology & Entomology, CONSECOL414: Advanced Conservation Management, Lecture, _Microscopic organisms: plant promoters and plant destroyers._
+ 2017 Stellenbosch University, Dept. of Conservation Ecology & Entomology, CONSECOL414: Advanced Conservation Management, Lecture, _A look into the microscopic world: lifelines or invisible threats._
+ 2017 Stellenbosch University, Dept. of Conservation Ecology & Entomology, CONSECOL414: Advanced Conservation Management, Field Course, Drie Kulien Nature Reserve.
+ 2016 Stellenbosch University, International Winter School, Biodiversity & Ecology Course, Lecture, _Surveying Phytophthora species with citizen science_.

### Co-direction

+ 2021 University of Washington, Human Centered Design and Engineering, Directed Research Group, Winter & Spring Quarters, _The UX of climate change: western redcedar dieback._

### Field Assistance

+ 2021 Evergreen State College, Environmental Studies Path Affiliation, _Field Ecology_
+ 2021 Green River College, BAS in Forest Resource Management program, _Forest Ecology_

### Workshop Instruction

+ 2019 University of Pretoria, Faculty of Natural and Agricultural Sciences, [_R for biology data science workshop series_](http://jmhulbert.github.io/r/bio/) _(5 sessions, 76 participants, packages: ggplot2 and dplyr)._
+ 2019 University of Pretoria, Forestry and Agricultural Biotechnology Institute, [_RStudio and R package workshop series_](http://jmhulbert.github.io/r/fabi/) _(5 sessions, 35 participants, packages: ggplot2, dplyr, vegan and Markdown)._
+ 2018 Stellenbosch University, Dept. of Conservation Ecology & Entomology, _RStudio and R package workshop series (4 sessions, 23 participants, packages: ggplot2, dplyr, and vegan)._

### Courses Prepared to Teach

  + Invasion / Disturbance Ecology
  + Forest Health and Protection
  + Forest Pathology
  + Forest Entomology
  + Methods of Citizen and Community Science

## Event Organization

### Workshops and Webinars

+ 2024 [_Preparing and Responding to Mediterranean Oak Borer in Washington State_](https://treehealth.wsu.edu/mob) (Virtual Workshop). 
+ 2024 [_Invasive species workshop and webinars for Tribal Audiences_](https://extension.wsu.edu/invasive-species/workshops/) (Virtual Workshop). 
+ 2023 [_Ravenholt Urban Forest Health Spring 2023 Webinars_](https://treehealth.wsu.edu/webinars/)
+ 2023 [_Invasive species workshop and webinars for Tribal Audiences_](https://extension.wsu.edu/invasive-species/workshops/) (Virtual Workshop).
+ 2022 E3 Washington Virtual Conference Workshop, _Schools as oases in urban heat islands: identifying the barriers_.
+ 2022 City of Tacoma, _Tacoma Tree Pest Identification Workshop_, City of Tacoma Waste Transfer Station and Nursery. 
+ 2022 Pacific Education Institute, _Urban Forestry Solutions Oriented Storylines_, Almendinger Conference Center, WSU Puyallup Research and Extension Center, Puyallup, Washington.
+ 2022 Washington Invasive Species Council & Washington State University, _Invasive Species Preparedness Resources for Tribal Nations Workshop_, Almendinger Conference Center, WSU Puyallup Research and Extension Center, Puyallup, Washington.
+ 2021 Webinar Co-Organizer, [Western Redcedar: Cultural and ecological reflections and dieback concerns](https://youtu.be/FrGBTo7HBnk), Treeline Webinar Series.
+ 2021 Webinar Co-Organizer, Arbutus ARME (https://www.arbutusarme.org), Inaugural Member Meeting -Spring.
+ 2021 Session Moderator (4 sessions), Washington Forest Owners' Winter School, Washington State University Extension.
+ 2020 Webinar Co-Organizer, Arbutus ARME (https://www.arbutusarme.org), Inaugural Member Meeting (Webinar).

### Conferences

+ 2024 Session Coordinator, _Public engagement to keep urban trees and communities healthy_, IUFRO 26th World Congress, Stockholm, Sweden. 
+ 2022 Conference Co-Organizer, [_Pacific Northwest Citizen Science Summit_](https://pnwcitsci.org/), Online Conference, Zoom.
+ 2022 Session Chair, Collaboration and Community Science, Human-Nature Systems, Salish Sea Ecosystem Conference. Online Conference, Zoom.
+ 2021 Conference Co-Organizer, [_Pacific Northwest Citizen Science Summit_](https://www.eventbrite.com/e/pnw-citizen-science-summit-tickets-167104687619), Online Conference, Zoom.
+ 2019 Session Coordinator, _Forest health defenders: empowering citizens to protect forests through research contributions_, IUFRO XXV World Congress, Curbita, Brazil.
+ 2018 Event Co-organizer, _South Africa Citizen Science Fair, International Citizen Science Day Event_, Kirstenbosch National Botanical Garden, Cape Town, South Africa.
+ 2017 Session Coordinator, _Early detection and monitoring of invasive forest pests and pathogens with citizen science_, IUFRO 125th Anniversary Congress, Freiburg, Germany.
+ 2014 Symposium Planning Committee, _Canopies to construction: the ecology, management and use of tomorrow’s forests_, Western Forestry Graduate Symposium, Corvallis, Oregon, USA.
+ 2013 Symposium Planning Committee, _Branching out: communicating forest research beyond academics_, Western Forestry Graduate Symposium, Corvallis, Oregon, USA.

### Invited Panel Participation

+ 2024 _Plant Procurement and Propagation Resources for Tribes_, Intertribal Nursery Council Meeting, Grand Ronde, Oregon.
+ 2024 _Community Science for Forest Health: A Plants and Climate Change Education (PLACCE) Conversation_, American Public Gardens.
+ 2023 _Bringing Youth Outside_, Healing Connections: Nature and Wellness Symposium.
+ 2023 _Climate Migration Workshop_, Human Centered Design and Engineering, University of Washington.
+ 2022 _Professional Q&A_, Northwest Innovative Forestry Summit, Forest Guild, UW Pack Forest, Eatonville, Washington. 
+ 2021 _Urban Forests: Climate Change Solution or Casualty?_ [Youtube](https://www.youtube.com/watch?v=H5YAX3MAzBg),Cascadia Climate Action, Climate Science on Tap Event.
+ 2015 _Is one tree worth a forest?_ World Forestry Congress, World Cafe Forest Health Session, Durban, South Africa.
+ 2013 _Maximizing your graduate education_, new student orientation panel, Graduate School, Oregon State University.

## Presentations

### North American Conferences

+ 2024 **Hulbert JM**, Elliott M, Chastagner G. _Community science links redcedar tree health to urban heat_. Conference for Advancing Participatory Sciences, Association for Advancing Participatory Sciences. 
+ 2024 Avila N, Bridges C, **Hulbert JM**. _Exploring the layers of science and communites impacted by climate change through the lens of tree health_. Urban Ecology and Conservation Symposium, Urban Ecosystem Research Consortium, Reed College, Portland, Oregon (not presenting author).
+ 2023 **Hulbert JM**, _Community engagement, Oomycetes and western redcedar dieback_, American Phytopathological Society annual conference, Denver, Colorado. 
+ 2023 **Hulbert JM**, _Community engagement for healthy forests_, Western International Forest Disease Work Conference, Sonoma, California.
+ 2023 Elliott M, **Hulbert JM**, Murray T, Chastagner G, _Identification of the sooty bark pathogen (*Cryptostroma corticale*) from hosts in multiple states_, Western International Forest Disease Work Conference, Sonoma, California (Poster Presentation).
+ 2023 Elliott M, **Hulbert JM**, Murray T, Chastagner G, _Detecting biological invasions with sentinel plantings at ports and urban points of dispersal in Washington State_, Western International Forest Disease Work Conference, Sonoma, California (Poster Presentation).
+ 2023 **Hulbert JM**, _Western redcedar dieback - open analyses of open data_, Washington GIS Association annual meeting, Tacoma, Washington.
+ 2023 **Hulbert JM**, _Community engagement can enhance biosurveillance_, Western Forest Insect Work Conference, Seattle, Washington.
+ 2022 **Hulbert JM**, Sooty Bark Disease - _Climate Change Time Bomb in the Pacific Northwest_, Partners in Community Forestry, Seattle, Washington.
+ 2022 **Hulbert JM**, _History of PNW CitSci and the Citizen Science Community_, Pacific Northwest Citizen and Community Science Summit (Virtual Presentation). 
+ 2022 **Hulbert JM**, _Sooty Bark Disease: Diagnostics & Research in the Pacific Northwest_, Pacific Northwest International Society of Arboriculture Meeting, Coure D'Alene, Idaho.
+ 2022 **Hulbert JM**, _Are Oomycetes associated with the dieback of western redcedar?_, 10th Meeting of the International Union of Forest Research Organizations, Working Party S07.02.09 - _Phytophthora_ in Forests and Natural Ecosystems Berkeley California.
+ 2022 **Hulbert JM**, _Forest Health Watch: empowering communities to keep trees healthy_, 10th Meeting of the International Union of Forest Research Organizations, Working Party S07.02.09 - _Phytophthora_ in Forests and Natural Ecosystems Berkeley California.
+ 2022 **Hulbert JM**, _Community engagement to accelerate research and learning about the dieback of western redcedar_. Salish Sea Ecosystem Conference. (Virtual Presentation).
+ 2022 **Hulbert JM**, _Community engagement can accelerate research about urban forest health issues_. Urban Ecology and Conservation Symposium, Urban Ecosystem Research Consortium, Portland Oregon. (Virtual Presentation).
+ 2021 **Hulbert JM**, _Western redcedar dieback as an indicator of the effects of climate change on cultural resources and tribal communities_, 2021 Rising Voices Workshop, [Virtual (Poster-walk) Presentation](https://public.tableau.com/app/profile/joey.hulbert/viz/2021RisingVoicesWorkshopPoster/Dashboard1)
+ 2021 **Hulbert JM**, _So, you want to start a citizen science project?_, 2021 Pacific Northwest Citizen and Community Science Summit, Virtual Presentation.
+ 2021 **Hulbert JM**, _Forest Health Watch: empowering community scientists to accelerate research_, Northwest Climate Conference (Online), Virtual Presentation.
+ 2021 **Hulbert JM**, _Urban Ecology and Conservation Symposium, Urban Ecosystem Research Consortium, Exploring the dieback of western redcedar as a symbol of the inequities in urban environments_. [Video Poster Presentation](https://www.youtube.com/watch?v=2xp6iStN_vM).
+ 2018 **Hulbert JM**, Burgess TI, Roets F, Wingfield MJ. 2018\. _Pathogen hunters: nonscientist engagement in plant disease research_, International Congress for Plant Pathology, Boston. Poster Presentation.
+ 2018 **Hulbert JM**, Burgess TI, Roets F, Wingfield MJ. 2018\. _The Cape Town Hypothesis Test: _Phytophthora_ in urban vs natural environments_, International Congress for Plant Pathology, Boston. Poster Presentation.
+ 2014 **Hulbert JM**, Morrell JJ, Hansen EM. 2014\. _Chemical treatment to sanitize _Phytophthora ramorum_ colonized timber products and mitigate the risk of accidental dissemination of Sudden Oak Death_. International Union of Forest Research Organizations, World Congress. Salt Lake City. Poster Presentation.
+ 2014 **Hulbert JM**, Rosenberger R. 2014\. _Forest G.U.M.P. The value of graduate-undergraduate mentorship programs_. International Union of Forest Research Organizations, World Congress. Salt Lake City. Poster Presentation.
+ 2014 **Hulbert JM**, Morrell JJ, Hansen EM. 2014\. _Potential of using boron for mitigation of Phytophthora ramorum in Douglas-fir logs_. International Research Group on Wood Protection 45th annual meeting. St. George, Utah. Oral Presentation.
+ 2014 **Hulbert JM**, Kamvar Z. 2014\. _Inspiration Dissemination: Science Communication for College Students_. American Association for the Advancement of Science Annual Meeting. Chicago, Illinois, Poster Presentation.
+ 2014 **Hulbert JM** 2014\. _The value of graduate-undergraduate mentorship programs_. Biennial Conference on University Education in Natural Resources Auburn University, Auburn, Alabama.
+ 2014 **Hulbert JM**, Kamvar Z. 2014\. _Inspiration Dissemination: Science Communication for College Students_. Biennial Conference on University Education in Natural Resources Auburn University, Auburn, Alabama.
+ 2012 **Hulbert JM**, Morrell J, Hansen E. 2012\. _Chemical treatment to sanitize Phytophthora ramorum colonized timber products_. Western International Forest Disease Work Conference, Tahoe City, California. Oral Presentation.
+ 2011 Hansen E, **Hulbert JM**, Reeser P, Sutton W, Kanaskie A. 2011\. _Sudden larch death? Larch susceptibility to Phytophthora ramorum_. Western International Forest Disease Work Conference, Leavenworth Washington. Poster Presentation.
\  

### International Conferences

+ 2024 **Hulbert JM**, Elliott M, Chastagner G. _Community engagement can enhance biosecurity_, IUFRO XXVI World Congress, Stockholm, Sweden. Oral Presentation.
+ 2024 **Hulbert JM**, Elliott M, Chastagner G. _Tree health and urban heat: engaging communities to study urban forest disparities_, IUFRO XXVI World Congress, Stockholm, Sweden. Poster Presentation.
+ 2024 **Hulbert JM**, Elliott M, Chastagner G. _Community engagement to accelerate research and learning about the dieback of western redcedar_, IUFRO XXVI World Congress, Stockholm, Sweden. Oral Presentation.
+ 2022 **Hulbert JM**. _Citizen science approaches: mass participation or structured monitoring of invasive species_.  International Plant Health Conference, London. [Recorded presentation](https://youtu.be/bvxTDj1ozZs). 
+ 2019 **Hulbert JM**. _Methods of public engagement in forest health research_, IUFRO XXV World Congress, Curitiba, Brazil. Oral Presentation.
+ 2019 **Hulbert JM**, Burgess T, Roets F, Wingfield MJ. _Non-scientist engagement in plant disease research in South Africa_, IUFRO XXV World Congress, Curitiba, Brazil. Oral Presentation.
+ 2017 **Hulbert JM**, Burgess T, Roets F, Wingfield MJ. _Public engagement to survey Phytophthora in South Africa_, IUFRO Working Party _Phytophthora_ in forests and natural ecosystems (7.02.09), Sapa, Vietnam. Oral Presentation.
+ 2017 **Hulbert JM**, Roux J, Burgess T, Roets F, Wingfield MJ. _Citizen science initiatives: opportunities to manage global forest pest challenges_, IUFRO 125th Anniversary Congress, Freiburg, Germany. Oral Presentation.
+ 2017 **Hulbert JM**, Roux J, Burgess T, Roets F, Wingfield MJ. _Cape Citizen Science: public engagement to detect and discover Phytophthora species in South Africa_, IUFRO 125th Anniversary Congress, Freiburg, Germany. Poster Presentation.
+ 2017 **Hulbert JM**, De Beer ZW, Wingfield MJ. _Cape Citizen Science: public engagement for plant disease research in a biodiversity hotspot_, International Botanical Congress, Shenzhen, China, Poster Presentation (not presenting author).
+ 2014 **Hulbert JM**, Morrell JJ, Hansen EM. _Wooden Vectors of Phytophthora ramorum: Are Douglas-fir Logs a Risk?_ Seventh Meeting of the IUFRO Working Party 7.02.09 _Phytophthora_ in Forests and Natural Ecosystems, Esquel, Argentina. Poster Presentation (not presenting author).
+ 2012 Peterson E, **Hulbert JM**, Hansen EM. _Roads and streams are not significant pathways for SOD spread in tanoak forests_. 6th IUFRO _Phytophthora_ in Forest and Natural Ecosystems. Cordoba, Spain. Oral Presentation (not presenting author).
\  

### South African Conferences

+ 2018 **Hulbert JM**. _Igniting conversations with community engagement: establishing citizen science projects in South Africa_, Science Forum South Africa, Pretoria, South Africa. Oral Presentation.
+ 2017 **Hulbert JM**, Roets FR. _Indigenous plant pathogens and their contributions to plant community diversity_, Fynbos Forum, Swellendam, South Africa. Oral Presentation.
+ 2017 **Hulbert JM**, Roets FR. _Revealing hidden threats to fynbos biodiversity with citizen science_, Fynbos Forum, Swellendam, South Africa. Oral Presentation.
+ 2017 **Hulbert JM**, Roux J, Burgess TI, Roets F, Wingfield MJ. _Methods of surveying plant pathogens with citizen science_, South African Society for Plant Pathology, 50th anniversary meeting, Champagne Sports Resort, KwaZulu-Natal Province, South Africa. Oral Presentation.
+ 2017 **Hulbert JM**, Roux J, Burgess TI, Roets F, Wingfield MJ. _Public engagement in South Africa's ecological research: the 'how' and 'why' of citizen science_, South African Association of Botanists, Annual Meeting, Cape Town, South Africa. Oral Presentation.
+ 2016 **Hulbert JM**, Agne MC, Roux J, Burges TI, Roets F, Wingfield MJ. _Records of Phytophthora invasions suggest that early detection programs should focus on urban environments_, DST-NRF Centre of Excellence for Invasion Biology Workshop, Non-native species in urban environments: patterns, processes, impacts and challenges, Stellenbosch, South Africa. Oral Presentation.
+ 2016 **Hulbert JM**. _Monitoring invasive species with citizen science: an international review_, Joint South African Association of Botanists-Southern Africa Society for Systematic Biology Conference, Bloemfontein, South Africa. Oral Presentation.
+ 2015 **Hulbert JM**. _Early detection and monitoring of invasive plant pests with citizen science_, DST-NRF Centre of Excellence for Invasion Biology Workshop, Evolutionary Dynamics of tree invasions: drivers, dimensions, and implications for management, Stellenbosch, South Africa. Oral Presentation.
\ 

### Symposia

+ 2023 Master Gardener Advanced Education Conference. _Backyard Citizen Science opportunities in the Northwest_. Oral Presentation. 
+ 2022 University of Washington Urban Forest Symposium. _Western redcedar trees as cultural resources in urban environments_. Pre-recorded presentation.
+ 2022 Washington State University Research Week, _Engaging community scientists in research about tree health and urban heat islands_. Virtual Presentation.
+ 2021 Washington State University Research Showcase, _Community science to keep forests healthy in the face of climate change_. Poster presentation.
+ 2021 Washington State University, 4th Annual plant Science Symposium, _Forest Health Watch: community science to accelerate research about the dieback of western redcedar_. Poster presentation.
+ 2020 Portland State University, Cedar Summit, _Understanding western redcedar dieback: the community science approach,_ Virtual Presentation.
+ 2020 Puyallup Watershed Symposium, Pierce County, _Forest Health Watch - community science for healthy forests,_ Webinar Presentation.
+ 2019 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Tree Protection Co-operative Program Annual Meeting, Phytophthora multivora: _local driver of plant diversity and global agent of bio-insecurity._
+ 2018 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Tree Protection Co-operative Program Annual Meeting, Phytophthora _diversity in southern Afrotemperate forests._
+ 2017 Stellenbosch University, Dept. of Conservation Ecology & Entomology, Research Day, _Introduction to Cape Citizen Science: A project to engage the public in plant disease research._
+ 2016 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Tree Protection Co-operative Program Annual Meeting, _Developing a citizen science program on tree health in South Africa._
+ 2016 University of Pretoria, Forestry and Agricultural Biotechnology Institute, NRF-DST Centre of Excellence in Tree Health Biotechnology Annual Meeting, _The history of_ Phytophthora cinnamomi _in South Africa._
+ 2015 University of Pretoria, Dept. of Plant & Soil Science Postgraduate Research Symposium, _Introduction to Cape Citizen Science: A project to engage the public in plant disease research._
+ 2014 Oregon State University, College of Forestry, Western Forestry Graduate Research Symposium, *Wooden vectors of* Phytophthora ramorum: *Are Douglas-fir logs really a risk?*
+ 2013 Oregon State University, College of Forestry, Western Forestry Graduate Research Symposium, _Chemical treatments to sanitize_ Phytophthora ramorum _colonized timber material and mitigate the risk of artificial Sudden Oak Death dissemination._
\ 

### Seminars and Lab Meetings

+ 2024 Green River College, Natural Resource Seminar, _Forest health issues, research, and student opportunities_.
+ 2023 Washington State University, Department of Plant Pathology Fall Seminar Series, _Citizen science and biosecurity- opportunities for plant disease monitoring and research_.
+ 2022 Washington State University, Department of Plant Pathology Fall Seminar Series, _Research needs for mitigating the emergence of sooty bark disease in the Pacific Northwest_ (Virtual Presentation).
+ 2021 USDA Forest Service, Forest Health and Protection (Region 6), monthly forest pathology meeting, _Sooty Bark Disease: climate change ‘time bomb’ in many broadleaf trees in the PNW_ (Virtual Presentation).
+ 2021 Washington State University, Department of Plant Pathology Spring Seminar Series, _Forest Health Watch: community engagement for healthy forests_ (Virtual Presentation).
+ 2021 Systematic Biology Seminar, Systematic Biology Programme, Uppsala University, Sweden  _Citizen science methods to accelerate research about forest health issues_ (Virtual Presentation).
+ 2020 Washington State University, Forestry Working Group meeting, _Forest Health Watch and the WSU forestry community_ (Virtual Presentation).
+ 2020 Washington State University, 4-H Eco-Stewards Program meeting, _Forest Health Watch - community science in the Pacific Northwest_ (Virtual Presentation).
+ 2020 University of Pretoria, Forestry and Agricultural Biotechnology Institute, _A quest for plant destroyers in the Cape Floristic Region: a story of the growth of an indigenous-plant pathologist_ (PhD Prestige Seminar). 
+ 2018 Stellenbosch University, Dept. of Conservation Ecology and Entomology, Roets, Oberlander, and Dryer Join Lab Meeting, _The Cape Town Hypothesis Test_.
+ 2017 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Thursday Morning Seminar Series, _The trade of live plants in Africa: a risk to tree health?_
+ 2016 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Research Discussion Seminar, _The role of scientists in society: developing a responsible protocol in case we discover an internationally regulated plant pathogen_.
+ 2016 University of Pretoria, Dept. of Plant and Soil Science, Fall Seminar Series, _Citizen science tools available for phytogeographical research in South Africa_.
+ 2016 Stellenbosch University, Dept. of Plant Pathology, Friday Forum Seminar Series, _Cape Citizen Science: community engagement to survey Phytophthora species in the fynbos_.
+ 2016 University of Pretoria, Forestry and Agricultural Biotechnology Institute, Thursday Morning Seminar Series, _Methods of sampling Phytophthora with citizen science_.
+ 2015 Oregon State University, Dept. of Botany and Plant Pathology, Spring Seminar Series, _Crowdfunding and citizen science applications in biology_.
+ 2013 Oregon State University, Dept. of Wood Science & Engineering, Spring Seminar Series, _Using wood science to mitigate the impact of Sudden Oak Death_.
\  

### Invited Talks

+ 2024 Indigenous Tree Teachings Workshop, _Western redcedar cultural resources in urban environments_ (recorded presentation), Winds of Change Alliance, Seattle, Washington. 
+ 2024 Climate Impacts Group, Lunch and Learn, _Trees and urban heat in the Northwest_, University of Washington, Seattle, Washington.
+ 2024 Green River College Forestry and Natural Resources Seminar, _Forest Health Issues, Research and Student Opportunities in Washington_.
+ 2023 Canadian Phytopathological Society, British Columbia Regional Meeting. **Keynote**: _Sharing the responsibility of biosecurity: engaging communities in plant disease monitoring_ (Virtual Presentation).
+ 2023 Environmental Justice Week, Highline College, _Urban forest equity and tree health in the Pacific Northwest_.
+ 2023 Washington Invasive Species Council Meeting, September. _Summary of the 2023 Invasive Species Workshop and Webinars for Tribal Audiences_
+ 2023 Palouse Discovery Science Center, Science Pub _Community minded scholarship: empowering people to address concerns with community science_. 
+ 2022 Washington Community Forestry Council Meeting, _Urban Forestry Programming at WSU_ (Virtual Presentation).
+ 2022 Northwest Indian Fisheries Commission, USDA Animal and PLant Health Inspection Service, Emergency Preparedness Response Management Training, _USDA APHIS INVASIVE Project Introduction_.
+ 2021 Washington Department of Natural Resources, Presentation to State Forester & Forest Health Division Leads, _Forest Health Watch: community engagement for healthy forests_ (Virtual Presentation).
+ 2021 Western International Forest Disease Workgroup, Climate Change Committee Update, _Western redcedar dieback update_ (Virtual Presentation).
+ 2021 Green River Coalition, Guest Seminar for Interns, _Forest Health Watch: community science to accelerate research_ (Virtual Presentation).
+ 2021 Seattle Climate Change Meetup Group, _Community scientists needed in forest health and climate change research_ (Virtual Presentation).
+ 2021 PlantAmnesty Member Event, _Community scientists needed to explore and understand the dieback of western redcedar_ (Virtual Presentation).
+ 2021 Bonneville Environmental Foundation, Treeline Practitioners Meeting, _Tools for community engagement: creating custom projects on iNaturalist_ (Virtual Presentation).
+ 2021 City of Tacoma, Nature and Enviornment Advisory Council Meeting, _Forest Health Watch: community engagement for healthy parks_ (Virtual Presentation).
+ 2021 Arbutus ARME, Spring member meeting, _TreeSnap and iNaturalist observation update_, (Virtual Presentation).
+ 2021 Forest Resource Management Faculty Meeting, Green River College,  _Forest Health Watch: community engagement for healthy forests_ (Virtual Presentation).
+ 2020 University of Washington, Urban Ecology Research Lab Meeting, _Exploring the dieback of western redcedar as a metaphor for the inequities in urban communities_ (Virtual Presentation).
+ 2020 Climate Resiliency Fund, Bonneville Environmental Foundation, Riparian Climate Corridors Project Extension Group Meeting, _Forest Health Watch - community science_ (Virtual Presentation).
+ 2020 King County, King County Conservation District Forestry Team Meeting, _Western redcedar dieback in King County_ (Virtual Presentation).
+ 2020 Washington State Department of Agriculture, Plant Protection Group Meeting, _Forest Health Watch - upcoming community science program_ (Virtual Presentation).
+ 2020 South King County Culture (SoCoCulture), Member Update, _Forest Health Watch - partnering with SoCuCulture to promote the Engaging Trees platform_ (Virtual Presentation).
+ 2020 Forest Adaptation Network, Bi-Annual Meeting, _Forest Health Watch - engaging communities in forest adaptation science_ (Virtual Presentation).
+ 2020 Seattle Urban Forestry Interdepartmental Team, Quarterly Meeting, _Forest Health Watch - upcoming community science program_ (Virtual Presentation).
+ 2020 Seattle Urban Forestry Commission, Monthly Meeting, _Forest Health Watch - community science in the Pacific Northwest_ (Virtual Presentation).
+ 2020 City of Seattle, Urban Forest Core Team, monthly Meeting, _Forest Health Watch - an upcoming community science program in the Pacific Northwest_ (Virtual Presentation).
+ 2020 Puyallup Watershed Initiative, Forest Community of Interest, Bimonthly Meeting, _Forest Health Defenders - Pacific Northwest citizen science - brainstorm and discussion_ (Virtual Presentation).
+ 2020 Forestry and Natural Resources Extension Coffee Hour, Oregon State University, _Forest Health Defenders - Pacific Northwest citizen science - brainstorm and discussion_ (Virtual Presentation).
+ 2020 EcoPhysiology Working Group, Reed College, Portland State University & WSU Vancouver, _Forest Health Defenders - Pacific Northwest citizen science - brainstorm and discussion_ (Virtual Presentation).
+ 2020 Urban Ecology Research Laboratory, University of Washington, _Seattle Urban Forest Atlas project proposal._
+ 2019 National Research Foundation, South African Agency for Science and Technology Advancement, FAMELAB Alumni Network Event, _Public engagement with citizen science in South Africa._
+ 2018 Transatlantic Science Education Cooperative, Annual Workshop, Stellenbosch University, _Cape Citizen Science: methods of youth engagement._
+ 2018 Iimbovane Outreach Workshop, Centre for Excellence in Invasion Biology, Stellenbosch University, _Microscopic organisms: why and how we study them._
+ 2018 Plant Conservation Unit, University of Cape Town, _Benefits and challenges of citizen science: the experiences of @CapeCitSci in South Africa._
+ 2018 Farm to Table Working Group, North Carolina State University, _Citizen science in South Africa: applications for agriculture_ (teleconference).
+ 2018 University of Pretoria, Forestry and Agricultural Biotechnology Institute, 20th Anniversary Meeting, _Inspiring a new generation of plant health specialists in Africa._
+ 2018 University of Washington, School of the Environment and Forests, Harvey Lab Meeting, _Citizen science and plant disease in South Africa._
+ 2016 Stellenbosch University, Dept. of Conservation Ecology and Entomology, Regional Universities Forum for Capacity Building in Agriculture (RuForum) visit, _Conserving Biodiversity with citizen science._
+ 2016 Agricultural Research Council, Stellenbosch University, Dept. of Plant Pathology, Pre-symposium Fungal Pathogens Discussion Group, ARC-PPRI 24th Interdisciplinary Symposium on Soil-borne Plant Diseases, _Public engagement to survey plant destroyers in South Africa._
+ 2016 Stellenbosch University, Centre of Excellence in Invasion Biology, Dept. of Zoology, Invasives in the Cape Discussion Group, _Is the greatest threat to South Africa's natural resources something we cannot see?_
+ 2015 Oregon State University, Dept. of Integrative Biology, Undergraduate Club, Spring Term Meeting, _Deciding how to impact the world: Issues, options, and tools._
+ 2015 Oregon State University, Science Communication Brown Bag Lunch Seminar Series, _Crowdfunding: creating new possibilities for science_.
+ 2014 Oregon State University, Science Communication Brown Bag Lunch Seminar Series, _The Process of Podcasting: Using College Radio to Communicate Science._
+ 2014 Oregon State University, College of Forestry, Researcher Teacher Partnerships: Making global climate change relevant in the classroom, Spring Workshop, _Invasive Species: Service Learning Opportunities for K-12._
+ 2014 Oregon State University, College of Forestry, Researcher Teacher Partnerships: Making global climate change relevant in the classroom, Spring Workshop, _Inspiring Science as Graduate Students._

### Competitive Presentations
#### Travel Awards

+ 2020 Washington State University, Innovation and Research Engagement Office, Research Week, _Washington State Forest Health and Climate Change Research Cooperative._

#### Science Communication

+ 2013 Scholars Insights, Oregon State University, _It only takes one spore to start an epidemic._

## Public Engagement

### Public Presentations

+ 2022 Forest Health Watch, _Tacoma Community Science Introduction_ (Virtual Presentation).
+ 2022 Washington State University, Forest Health Watch. _Sooty Bark Disease Bi-Monthly Information Sessions_ (Virtual Presentation). 
+ 2022 Forest Health Watch, _Monthly Research Updates_ (Virtual Presentations).
+ 2022 Washington State University, WSU Forestry Webinar, Western Redcedar Diebak Webinar [_Community science to advance knowledge and learning about western redcedar dieback_](https://www.youtube.com/watch?v=reWd-pzg1qA) (Virtual Presentation).
+ 2022 Washington State University, _Forest Health Watch - Collaborator Update Meetings (2 events)_ (Virtual Presentation).
+ 2021 Tacoma Tree Foundation, Growing Skills Webinar Series, _Tracking sooty bark disease in the Pacific Northwest_ (Virtual Presentation).
+ 2021 Comox Valley Nature (Vancouver Island, BC), _Western Redcedar Dieback and Community Science in the Pacific Northwest_ (Virtual Presentation).
+ 2020 Tacoma Tree Foundation, Growing Skills Webinar Series, _Forest Health Watch - recognizing signs and symptoms of tree pests and diseases in our neighborhoods_ (Webinar Presentation).
+ 2020 Washington State University, _Forest Health Watch - Collaborator Update Meetings (3 events)_ (Virtual Presentation).
+ 2018 South African Citizen Science Project Fair, International Citizen Science Day, Old Mutual Conference Center, Kirstenbosch National Botanical Garden, _Cape Citizen Science._
+ 2018 Friends of Brackenfell Nature Reserve, Brackenfell Nature Reserve, monthly meeting, _How citizens can protect the Cape Floral Kingdom from new plant diseases._
+ 2018 Wildlife and Environment Society of South Africa, Tygerberg Nature Reserve, Big Friends Group Event, _How citizens can protect the Cape Floral Kingdom from new plant diseases._
+ 2017 South African National Biodiversity Institute, Kirstenbosch National Botanical Garden, Room To Grow Wednesday Talks Series, _Cape Citizen Science: plant disease in the fynbos._

### Youth Engagement Activities

+ 2024 Muckleshoot Indian Tribe Summer Youth Crew, Natural Resources, Tomanamus Forest, _Redcedar Adaptation Trial Measurements_
+ 2024 Muckleshoot Indian Tribe Summer Youth Crew, Natural Resources, Tomanamus Forest, _Forest Health Hike_
+ 2024 Forest Management Class, Science and Math Institute, Tacoma Washington, _Western redcedar park study introduction_.
+ 2024 Forest Management Class, Science and Math Institute, Tacoma Washington, _Forest Health and Invasive Species walk_.
+ 2023 Forest Management Class, Science and Math Institute, Tacoma Washington, _Forest Health and Invasive Species walk_.
+ 2023 Ecology Club, Chief Leschi, Puyallup Tribe of Indians School District, _Soil sampling and monitoring_.
+ 2022 Northwest Youth Corps, Capitol Land Trust, Inspiring Kids Preserve, _Forest Health and Invasive Species walk_. 
+ 2022 Muckleshoot Tomanamus Forest, Muckleshoot Tribal College - Early College Program and College and Career Education Opportunities Program, _Invasive Species_ (1 event).
+ 2022 Ecology Club, Chief Leschi, Puyallup Tribe of Indians School District, Ecology Club, _Earth Day tree planting_.
+ 2022 Hilltop Heritage Middle School, Thrive Program, _Educational walk and tree identification_ (1 event), Point Defiance Park, Tacoma, Washington.
+ 2021 Mount Tahoma High School, Botany class _Forest Walk at Lincoln Tree Farm_, Spanaway, Washington. 
+ 2021 Muckleshoot Tribal College - Early College Program, _Educational Walks in Tomanamus Forest_ (2 events), Tomanamus Forest, Green Water, Washington.
+ 2021 Muckleshoot Tribal College - Early College Program, _Research Tour_, Washington State University, Puyallup Research and Extension Center.
+ 2018 Kluitjieskraal and Waterval Junior Rangers, _Part 2: Collecting bark and ambrosia beetles_, Cape Nature, Wolseley.
+ 2018 Littlewood Primary, _Part 2: Collecting bark and ambrosia beetles_, Cape Nature, Wolseley.
+ 2018 Littlewood Primary, _Part 1: Collecting bark and ambrosia beetles_, Cape Nature, Wolseley.
+ 2018 Kluitjieskraal and Waterval Junior Rangers, _Part 1: Collecting bark and ambrosia beetles_, Cape Nature, Wolseley.
+ 2017 SANParks Junior Rangers, _Hike to De Mond_, Cape Point, Table Mountain National Park.
+ 2017 Noordhoek Primary, _Cape Citizen Science Presents: Cape Nature Junior Ranger Adventures in Rochepan Nature Reserve_, Cape Nature, Veldrift.
+ 2017 Littlewood Primary, _Cape Citizen Science Presents: Cape Nature Junior Ranger Adventures in Drift Sand Nature Reserve_, Cape Nature, Blue Downs.
+ 2017 Se7en +1 homeschool group, _Cape Citizen Science Presents: Lab Visit with Se7en +1_, Stellenbosch University, Stellenbosch.
+ 2017 Fish Hoek Girl Guides, _Adventures with First Fish Hoek Girl Guides_, Fish Hoek.
+ 2017 Se7en +1 homeschool group, _Mountain hike with Seven+1_, Fish Hoek.
+ 2017 Mamre Girls Brigade, _Cape Citizen Science Presents: Adventures in Silwer Stream._ Cape Nature, Mamre.
+ 2017 South African Education and Environment Project, _SAEP and Cape Citizen Science Present: Adventures in Helderberg Nature Reserve_, three activities (July 29, August 5, and October 7), Cape Town Municipality, Somerset West,
+ 2017 South African Education and Environment Project, _SAEP and Cape Citizen Science Present: Adventures in Cape Point_, three activities (June 10, 17 and 24), Cape Point, Table Mountain National Park.
+ 2017 Vision Afrika, _Pathogen hunting in Jonkershoek Nature Reserve on Earth Day_, Jonkersheok Nature Reserve, Stellenbosch.
+ 2016 Helderberg Eco-Rangers, _Sampling streams for Phytophthora and monitoring stream health with miniSASS_, Edward Wood Environmental Education Center, Somerset West.
+ 2016 Helderberg Eco-Rangers, _Training to be citizen scientists: reporting dying plants with IspotNature_, Helderberg Eco-Rangers, Edward Wood Environmental Education Center, Somerset West.
+ 2016 Four Cape Town Scout Troops, *Cape Citizen Science: plant disease on Hoys Koppie*, Hermanus, Scout excursion.
+ 2016 Helderberg Eco-Rangers, _Disease in our fynbos_, Edward Wood Environmental Education Center, Somerset West.
+ 2015 Se7en +1 homeschool group, _Sampling in Kirstenbosch National Botanical Garden_, South African National Biodiversity Institute, Cape Town.
+ 2014 Wood Magic Volunteer, _Forest products in everyday materials_, World Forestry Institute, Portland, Oregon.
+ 2013 Wood Magic Volunteer, _Forest products in everyday materials_, World Forestry Institute, Portland, Oregon.

### Outdoor Events

+ 2023 _Tacoma Tree Foundation_, Maple Health Watch walk and happy hour, Franklin Park, Tacoma, Washington.
+ 2022 _Tacoma Tree Foundation_, Private hike with donor, Madrone Ecology, Point Defiance, Tacoma, Washington.
+ 2022 _City of Renton and Renton School District_, Redcedar Tree Planting, Black River Riparian Area, Renton, Washington.
+ 2022 _Tacoma Tree Foundation_, Redcedar Tree PLanting, Swan Creek, Tacoma, Washington.
+ 2021 _Issaquah Alps Trail Club_, Forest Health, Tiger Mountain, Issaquah, Washington.
+ 2021 _Tacoma Tree Foundation_, Madrone Ecology, Swan Creek, Tacoma, Washington.
+ 2020 _Arbutus ARME_, Madrone Ecology, Point Defiance, Tacoma, Washington.

### Promotional Table Events

+ 2024 Forest Health Watch, MetroParks Tacoma Fall Plant Sale, Wright Park, Tacoma, Washington.
+ 2024 Forest Health Watch, North Tacoma Cushman Fair, Tacoma, Washington.
+ 2024 WSU Puyallup Research and Extension Center Programming, State Fair, Puyallup, Washington.
+ 2024 WSU Puyallup Research and Extension Center Programming, Spring Fair, Puyallup, Washington.
+ 2024 Forest Health Watch, South Sound Sustainability Fair, Tacoma, Washington.
+ 2024 Forest Health Watch, Oregon Tree School Clackamas, Clackamas Community College, Oregon City, Oregon.
+ 2024 WSU Ravenholt Urban Forest Health Lab, WSU Small Forest Landowner's Winter School, Green River College, Auburn, Washington.
+ 2023 WSU INVASIVES-R Project, Affiliated Tribes of Northwest Indians, Winter Convention, Portland, Oregon.
+ 2023 WSU Puyallup Research and Extension Center, Tomanamus Community Day, Muckleshoot Indian Tribe, Green Water, Washington.
+ 2023 Forest Health Watch, Fall State Fair - NW Outdoors Exhibit, Puyallup, Washington.
+ 2023 WSU INVASIVES-R Project, Affiliated Tribes of Northwest Indians, Annual Convention, Confederated Tribes of Chehalis Indian Reservation, Great Wolf Lodge, Grand Mound, WA.
+ 2023 WSU INVASIVES-R Project, Northwest Intertribal Agricultural Council Regional Meeting, Pendleton Oregon.
+ 2023 Forest Health Watch, Tacoma Garden Festival, Tacoma, Washington.
+ 2023 Forest Health Watch, South Sound Sustainability Fair, Tacoma, Washington.
+ 2023 Forest Health Watch, Spring State Fair - NW Outdoors Exhibit, Puyallup, Washington.
+ 2022 Forest Health Watch, Focus on Forestry, Monroe, Washington.
+ 2022 WSU Puyallup Research and Extension Center, Tomanamus Community Day, Muckleshoot Indian Tribe, Green Water, Washington.
+ 2022 Forest Health Watch, Climate Science on Tap, Seattle, Washington.
+ 2022 WSU INVASIVES Project, Affiliated Tribes of Northwest Indians Annual Convention, Tulalip, Washington.
+ 2022 Forest Health Watch, South Sound Sustainability Fair, Tacoma, Washington.
+ 2022 Forest Health Watch, Tacoma Tree Foundation, Hilltop Tree Giveaway, Tacoma, Washington.
+ 2018 Science Forum South African, Council for Scientific and Industrial Research, Pretoria.
+ 2018 Biodiversity Careers Day, Kirstenbosch Research Centre, Cape Town.
+ 2017 Science Forum South African, Council for Scientific and Industrial Research, Pretoria.
+ 2017 National Science Week_,_ African Institute of Mathematical Sciences, Khayelitsha. 
+ 2017 Open Day, Faculty of AgriSciences, Stellenbosch University.
+ 2016 Hermanus Botanical Society Flower Festival, Hermanus.
+ 2016 Funky Fynbos Festival, Gaansbai.
+ 2015 Arbor Week Expo, Stellenbosch.
+ 2013 Spring Discovery Days, Oregon State University.
+ 2013 Fall Discovery Days, Oregon State University.

## Stakeholder Engagement 
### Presentations

+ 2024 Washington Native Plant Society, _Forest Health Watch: keeping trees healthy together_ South Sound Chapter, Olympia, Washington. 
+ 2024 Preparation and Response to Mediterranean Oak Borer in Washington Workshop, _Community science to keep garry oaks healthy_ (Virtual Presentation). 
+ 2024 United States Botanical Garden (DC) Hosted Webinar, Plants and Climate Change Education (PLACCE) session, [_Community Science for Forest Health with Dr. Joey Hulbert and Nina Avila_](https://www.youtube.com/watch?v=e_1Bc0DgufY) (Virtual Presentation).
+ 2024 Washington Naturalists, _Forest Health Watch - keeping trees healthy together_, Washington State University  (Virtual Presentation).
+ 2024 Online Workshops and Webinars for Tribal Audiences, _Enriching tribal management and resilience to invasive species with co-designed educational resources_, (Virtual Presentation). 
+ 2024 Online Workshops and Webinars for Tribal Audiences, _Keeping berry patches healthy- invasive species threats to Vaccinium species_, (Virtual Presentation). 
+ 2024 Online Workshops and Webinars for Tribal Audiences, _Invasive species impacts, options and resources_, (Virtual Presentation). 
+ 2024 Oregon Tree School Clackamas, _Forest Health Watch - keeping trees healthy together_, Oregon City, Oregon.
+ 2024 King County Rural Forest Commission _Forest health issues and research in Western Washington_ (Virtual Presentation). 
+ 2024 WSU Small Forest Landowner Winter School, _Western redcedar dieback: updates from WSU research_ Green River College, Auburn, Washington. 
+ 2024 USDA APHIS Emergency Preparedness Training, _Enriching tribal management and resilience to invasive species with co-designed educational resources_ Quinault Indian Nation, Ocean Beach, Washington (Virtual Presentation).
+ 2024 Northwest Natural Resources Group, Fireside Chat, _Backyard citizen science opportunities in the Northwest_
+ 2024 Tacoma Public Schools, Climate Action Group, _Trees and urban heat in Tacoma_
+ 2023 Forest Health Watch, November Collaborator Updates (3 meetings with presentations)
+ 2023 Annual Training Conference, Pacific Northwest Chapter of the International Society of Arboriculture, _Western redcedar dieback in the urban environment_, Tacoma, Washington.
+ 2023 Intertribal Agriculture Council, Pacific Northwest Region Meeting, _No-cost educational materials to amplify awareness and mitigate the impacts of invasive species_.
+ 2023 Washington State University Extension Western Washington Family Field Day, _Emerging Diseases in the Pacific Northwest_.
+ 2023 Cascadia User Group of Open Source (CUGOS) meeting, _Western redcedar dieback: open analyses of open data_, Seattle, Washington.
+ 2023 Port of Tacoma, Invasive Species Workshop, _Sentinel Plantings in Tacoma: a tool for detecting new arrivals of invasive species_, Tacoma, Washingotn.
+ 2023 Ravenholt Urban Forest Health Webinars, _Tacoma Sooty Bark Disease Vulnerability Study_ (Online Webinar).
+ 2023 South Sound Mushroom Club, _Fungi and tree health in the Pacific Northwest_, Olympia, Washington.
+ 2023 Northwest Natural Resources Group, Fireside Chat, _Monitoring tree health: community mapping to study western redcedar dieback_.
+ 2022 Northwest Innovative Forestry Summit, Forest Guild, _Forest Health Watch - data for public engagement and project implementation_, UW Pack Forest, Eatonville, Washington. 
+ 2022 Washington State University Extension Online Field Day, _Emerging Diseases in the Pacific Northwest_ (Pre-Recorded Online Presentation). 
+ 2022 Pacific Northwest International Society of Arboriculture Meeting, _Sooty Bark Disease: Diagnostics & Research in the Pacific Northwest_ (Pre-Recorded Online Presentation). 
+ 2022 Affiliated Tribes of Northwest Indians, Natural Resource Committee, _Brief introduction to WSU /USDA APHIS INVASIVE Project_.
+ 2022 Intertribal Agriculture Council, Pacific Northwest Region Meeting, _FY22 USDA APHIS PPA 5.0595: Increasing Native Vigilance, Awareness and Surveillance of Invasions via Education (INVASIVE) Project_.
+ 2022 WSU Master Gardeners, Lewis County Chapter, _Community science to study the dieback of western redcedar_.
+ 2022 Washington State University, Master Naturalist Programming, _Community science to study the dieback of western redcedar_. (Two Virtual Presentations).
+ 2022 Washington Native Plant Society, Koma Kushan Chapter, _Community scientists needed for Western redcedar dieback in Pacific Northwest_. (Virtual Presentation).
+ 2022 Selkirk Alliance for Science, _Community Science for western redcedar research_ (Webinar Presentation).
+ 2022 Washington State Department of Transportation, Revegetation Climate Change Discussions _Forest Health Watch and western redcedar dieback research_ (Webinar Presentation).
+ 2022 Washington State University, Washington Forest Owners' Winter School, _Sooty Bark Disease in the PNW - what to look for in your maple trees_ (Webinar Presentation).
+ 2022 City of Seattle, _Sooty Bark Disease in the Pacific Northwest_, Integrated Pest Management and Recertification Webinar (Virtual Presentation).
+ 2022 South Sound Educators, Science Leadership Collaborative, _Linking ecology education and research with iNaturalist_ (Virtual Presentation).
+ 2021 - 2022 Washington State University, _Forest Health Watch - Research Updates_, Montly (June-Dec) (Virtual Presentations).
+ 2021 Issaquah Alps Trail Club, _Community scientists needed for Western redcedar dieback in Pacific Northwest_. (Virtual Presentation).
+ 2021 Idaho Native Plant Society, Kinnikinnick Chapter, _Community scientists needed for Western redcedar dieback in Inland Northwest_. (Virtual Presentation).
+ 2021 Idaho Native Plant Society, White Pine Chapter, _Community scientists needed for Western redcedar dieback in Inland Northwest_. (Virtual Presentation).
+ 2021 Montana Native Plant Society, Flathead and Kelsey chapters _Community scientists needed for research about western redcedar dieback_ (Virtual Presentation).
+ 2021 USFS Region 6 Advanced Silviculture Training _Community science to accelerate research and enhance biosecurity in the Pacific Northwest_ (Virtual Presentation).
+ 2021 WSU Extension Lewis County Invasive Species Workshop _Keeping trees healthy in Washington - WSU research and extension services_ (Virtual Presentation).
+ 2021 Washington State University, Master Gardener Advanced Diagnostic Training Workshop _Forest Health Watch: community science to accelerate research_ (Virtual Presentation).
+ 2021 Shoreline Green Cities Partnership Forest Stewards Training, _Community scientists needed for redcedar dieback research_ (Virtual Presentation).
+ 2021 Redmond Green Cities Partnership Forest Stewards Training, _Community scientists needed for redcedar dieback research_ (Virtual Presentation).
+ 2021 Issaquah Green Cities Partnership Forest Stewards Training, _Community scientists needed for redcedar dieback research_ (Virtual Presentation).
+ 2021 Washington State University Extension SW Washington Forestry Tech Series, _Tracking forest health issues with iNaturalist_ (Virtual Presentation).
+ 2021 Seattle Green Cities Partnership Forest Stewards Training, _Western redcedar dieback in Seattle_ (Virtual Presentation).
+ 2021 Thurston County Master Gardeners, _Forest health concerns and community science in the Pacific Northwest_ (Virtual Presentation).
+ 2021 Portland Metro, monthly conservation teams meeting, _Forest Health Watch: community science to accelerate research_ (Virtual Presentation).
+ 2021 WSU Grays Harbor & Pacific County Master Gardeners, _Forest Health Watch: community science to accelerate research_ (Virtual Presentation).
+ 2021 Bainbridge Island Watershed Council, _Forest Health Watch: community engagement for healthy forests_ (Virtual Presentation).
+ 2021 Washington State University, _Pacific Northwest Forest Biosurveillance Training (June)_ (Virtual Presentation).
+ 2021 Washington State University, _March Forest Health Watch - Collaborator Update Meetings (4 events)_ (Virtual Presentation).
+ 2021 Washington State University, Washington Forest Owners' Winter School, _Western redcedar dieback: what’s happening and how you can help_ (Webinar Presentation).
+ 2021 Duwamish River Re-vegetation Partners Meeting, King County, _Insights for healthy restoration practices_ (Virtual Presentation).
+ 2020 Green Cities Partnership Network Meeting, _Forest Health Watch - keeping forests healthy_ (Virtual Presentation).
+ 2020 Washington State University, _November Forest Health Watch - Collaborator Update Meetings (3 events)_ (Virtual Presentation).
+ 2017 South African National Biodiversity Institute, *Introduction to Phytophthora*, Plant Pest Monitoring and Prevention Workshop, International Plant Sentinel Network, Kirstenbosch National Botanical Garden, November 6-7, 2017.
+ 2017 South Africa National Parks, *Forest Phytophthoras: invisible threats or contributors to plant community diversity?* Garden Route National Park SANParks Office, Knysna, South Africa.
+ 2017 Cape Town Municipality, _Plant disease in the Cape Floristic Region_, Branch Meeting, Cape Town.
+ 2017 Cape Town Municipality, Cape Nature, World Wildlife Foundation, _Plant disease in the Cape Floristic Region_, BioNet Steering Committee Meeting, Cape Town.
+ 2016 South Africa National Parks, _Cape Citizen Science: Sampling Phytophthora with Citizen Science_, Research Committee Feedback Discussion, Cape Research Centre, Tokai, Cape Town.
+ 2016 Cape Nature, _Involving Cape Nature to study dying plants in the fynbos_, Eastern Division Quarterly Ecological Meeting, George.
+ 2016 Cape Nature, _Engaging citizens in research through workshops and targeted sampling_, Central Division Quarterly Ecological Meeting, Fernkloof Nature Reserve, Hermanus.
+ 2016 Cape Nature, _Community driven research about plant disease in the fynbos_, Western Division Quarterly Ecological Meeting, Porterville.

### WSU Puyallup REC Tours

+ 2024 Washington State Legislative Tour - WSU Research and Extension
+ 2024 Northwest Youth Corps, Tacoma Urban Community Forestry Spring Crews.
+ 2024 Tacoma Community College, Environmental Science students, Spring.
+ 2023 Representative Kim Schrier and Staffers
+ 2023 Tacoma Community College, Environmental Science students, Fall.
+ 2023 Pacific Lutheran University, Botany course students
+ 2023 Tacoma Community College, Environmental Science students, Spring. + 2023 Tacoma Community College, Math Engineering and Science Achievement (MESA) students.
+ 2022 Conservation District Foresters.
+ 2022 Pierce County Americorps Crew.
+ 2022 City of Tacoma, Washington Conservation Corps Crew.

### Community Science Events

+ 2023 Issaquah Alps Trail Club, Northwest Tiger Mountain, Issaquah, Washington.
+ 2022 Tacoma Tree Foundation, Redcedar walk, Swan Creek, Tacoma, Washington.
+ 2022 Issaquah Alps Trail Club, Squak Mountain, Issaquah, Washington.
+ 2022 Issaquah Alps Trail Club, North Tiger Mountain, Highline Trail, Issaquah, Washington.
+ 2021 Transition Fidalgo and Friends, Anacortes, Washington.  

### Plant Health Workshops

+ 2023 Sooty Bark Disease Tour, Annual Training Conference, Pacific Northwest Chapter of International Society of Arboriculture. 
+ 2022 Forest Health Watch, Wapato Park Tour, Co-hosted with Forterra and City of Tacoma Open Spaces, Tacoma, Washington. 
+ 2017 South African National Parks, _Hunting for_ Phytophthora _in West Coast National Park_, SANParks office, Langebaan, West Coast.
+ 2017 Stellenbosch Municipality, _Surveying_ Phytophthora _in Jan Marais Nature Reserve_, Stellenbosch.
+ 2016 Cape Nature, _Surveying_ Phytophthora _in Marloth Nature Reserve_, Marloth Nature Reserve, Swellendam.
+ 2016 South African National Biodiversity Institute, _Recognizing plant disease, sampling soil, and testing hypotheses_, Harold Porter Botanical Garden, Bettys Bay.
+ 2016 Stellenbosch University, _Recognizing plant disease and sampling soil for Phytophthora spp.,_ Stellenbosch University Botanical Garden, Stellenbosch
+ 2016 South African National Biodiversity Institute, _Hypothesis testing in Kirstenbosch National Botanical Garden with Citizen Science_, Kirstenbosch National Botanical Garden, Kirstenbosch Garden Office, Cape Town.
+ 2016 South African Botanical Society, _Surveying_ Phytophthora _species in Fernkloof Nature Reserve_, Fernkloof Nature Reserve Hall, Hermanus.
+ 2016 South Africa National Parks, Surveying _Phytophthora_ species in Agulhas National Park, SANParks Office, Agulhas.
+ 2016 South African National Biodiversity Institute, Phytophthora _soil baiting in the Protea Garden_, Kirstenbosch National Botanical Garden, Kirstenbosch Garden Office, Cape Town.
+ 2016 South Africa National Parks, _Sampling dying plants and the Breede river in Bontebok National Park_, Bontebok National park, Swellendam.
+ 2016 South African National Biodiversity Institute, _Recognizing plant disease: why and how_, Kirstenbosch National Botanical Garden, Kirstenbosch Garden Office, Cape Town.
+ 2016 South Africa National Biodiversity Institute, _Introduction to Phytophthora: plant destroyers in South Africa_, Kirstenbosch National Botanical Garden, Kirstenbosch Garden Office, Cape Town.

## Mentorship and Supervision
  
  + 2024 Isaih Montejano. Full-time Lab and Field technician. 
  + 2023 Jah'Niya Myers. Internship Project (Senior), College of Agricultural, Human, and Natural Resource Sciences Internship Program, Washington State University 
  + 2023 Anne Marie Ring. Part-time Summer Lab and Field technician, University of Puget Sound Biology and Geography undergraduate student. 
  + 2022 Noah Willards. Part-time Lab Technician and prospective graduate student. 
  + 2022 Fig Dewitz. Part-time Lab and Field Technician. 
  + 2022 Taylor McNees. Capstone Project and Lab Technician, Microbiology, University of Washington Tacoma
  + 2022 Hibaaq Arte, Capstone Project (Senior), Environmental Studies, University of Washington
  + 2022 Daviti Vardishvili, Internship Project (Junior), High-Value Agriculture Research and Extension Experiences for Undergraduate Students (REEU) Program, Washington State University
  + 2022 Grant Irey, Internship Project (Freshmen), College of Agricultural, Human, and Natural Resource Sciences Internship Program, Washington State University
  + 2022 Nicole Vonberckefeldt, Capstone Project (Senior), Natural Resources, Green River College
  + 2022 Jennifer Olson, Capstone Project (Senior), Natural Resources, Green River College
  + 2022 Lyndsay Felthoven, Capstone Project (Senior), Environmental Studies, University of Washington
  + 2022 Angela Mabel Gaither, Capstone Project (Senior), Environmental Studies, University of Washington
  + 2021 Brieanne Laia & Hailey Dilow, Marine Chemistry Science Project (Grade 12), Bellarmine Prepratory Highschool, Tacoma, Washington.
  + 2018 Eric Norton, BSc Honors (4th year), Dept. of Conservation Ecology and Entomology, Stellenbosch University.
  + 2018 Ashleigh Basel, BSc Honors (4th year), Dept. of Conservation Ecology and Entomology, Stellenbosch University.
  + 2017 Grég Thiry, MSc Environmental Education,  Université of Montpellier, France. South African Environmental Education Project Intern.
  + 2017 Nicolas Louw, BSc Honors (4th year), Dept. of Conservation Ecology and Entomology, Stellenbosch University.
  + 2017 Adam Wentzel, Work Integrated Learning Student, Cape Nature, Jonkershoek Nature Reserve, Dept. of Biodiversity and Conservation, Cape Peninsula University of Technology.
  + 2017 Tara Nair Van Ryneveld, BSc Honors (4th year), Plant Conservation Unit, Dept. of Biological Sciences, University of Cape Town.
  + 2017 Liza-Marie Dippenaar, BSc Plant Pathology 4th year project, Dept. of Plant Pathology, Stellenbosch University.
  + 2017 James Coldrey, BSc Plant Pathology 4th year project, Dept. of Plant Pathology, Stellenbosch University.
  + 2016 Jeff Groenewald, BSc (3rd year), Biodiversity and Ecology, Dept. of Botany and Zoology, Stellenbosch University.
  + 2014 Emma Buczkowski, BSc Zoology, Dept. of Botany & Plant Pathology Undergraduate Mentorship Program (BUDS) Oregon State University.
  + 2014 Joey DeSheilds, BSc Molecular and Cell Biology, Dept. of Botany & Plant Pathology Mentorship Program (BUDS), Oregon State University.
  + 2014 Kayla Nass, BSc Wood Science and Engineering, Hourly Morrell Lab Student Employee, Oregon State University.
  + 2014 Al Pancoast, BSc Forest Engineering, Forestry Graduate Undergraduate Mentorship Program (GUMP), Oregon State University.
  + 2014 Alex Abair, BSc Botany & Plant Pathology, Hourly Hansen Lab Student Employee, Oregon State University.
  + 2013 Josh Petitmermet, Hourly Hansen Lab Student Employee, Oregon State University.
  + 2013 Jake Kotche, Hourly Hansen Lab Student Employee, Oregon State University.
  + 2013 Patrick Duyck, BSc Forest Engineering, Personal Initiative.

## Mentorship Outcomes

 + McNees T, **Hulbert JM**, Elliott M, Chastagner G. 2023. Sooty bark disease of bigleaf maple: A microscopic threat to the world’s largest maple species, Puyallup Watershed Symposium. 
 + McNees T 2023. NSF Graduate Research Fellowship Proposal: Population genomics of _Cryptostroma corticale_.  
  + Olson J, Vonberckefeldt N, **Hulbert JM** 2022. Oomycete communities associated with redcedar on Green River College campus, Green River College Capstone Presentation.
  + Vardishvili D, Shrader K, Harvey S, **Hulbert J**, Chastagner G. 2022. Post-harvest hydration treatment effects on the vase life of Peonie, Washington State University, Summer Undergraduate Research Symposium. (Poster Presentation.) 
  + Gaither A, Billo T, **Hulbert JM** 2022. Redcedar dieback and urban heat in Renton, Environmental Studies Capstone Project Presentations, University of Washington. Poster Presentation. 
  + Felthoven L, Billo T, **Hulbert JM** 2022. Redcedar dieback and environmental health disparities in Seattle, Environmental Studies Capstone Project Presentations, University of Washington. Oral Presentation. 
  + Laia B, Dilow H, **Hulbert J** 2021. Phytophthora species associated with unhealthy red alder trees at Titlow Park, Bellarmine Prepatory Highschool Science Fair.
  + Basel A, **Hulbert JM**, Midgley G, Jacobs S, Dreyer L, Roets F. 2018\. Disease or drought? A physiological analysis on the effects of _Phytophthora_ infection and water stress on _Leucadendron argenteum_, Fynbos Forum, Worcestor, South Africa. Oral Presentation.
  + Groenewald J, Roets F, **Hulbert JM.** 2017\. _Phytophthora cinnamomi_: a driver behind endangered flora in the CFR?, South African Association of Botanists, Annual Meeting, Cape Town, South Africa. Poster Presentation.
  + Louw NL, Roets F, **Hulbert JM.** 2017\. The diminishing silver lining: re-evaluating the microscopic threats to South Africa's silver tree, Fynbos Forum, Swellendam, South Africa. Oral Presentation.

## Professional Development

  + 2024 [Faculty Success Program](https://www.ncfdd.org/sessions/fspspring2025), National Center for Faculty Diversity and Development. 
  + 2022 [Columbia River Inter-Tribal Fish Commission](https://critfc.org/), Aquatic Invasive Species Workshop, Aquatic Ecology Laboratory, Washington State University Vancouver. 
  + 2021 [Integrating Climate into Hazard Mitigation Plans (Western Region)](http://www7.nau.edu/itep/main/tcc/docs/training/BLR_FEMA%20Course%20Description.pdf), Tribes & Climate Change Program, Institute
for Tribal Environmental Professionals, Northern Arizona University.
  + 2021 [CC101: Introduction to Climate Change Adaptation Planning for Tribes](http://www7.nau.edu/itep/main/tcc/Training/Trainings), Tribes & Climate Change Program, Institute
for Tribal Environmental Professionals, Northern Arizona University.
  + 2021 Software/Data Carpentry workshop at the UW eScience Institute, University of Washington.
  + 2021 Partnership Development Training, USDA Forest Service
  + 2020 PI Roles and Responsibilities Training, Washington State University.
  + 2020 Working with Industry 101, Washington State University.
  + 2020 Study Circle on Racism and Equity, Washington State University.
  + 2018 Citizen science and youth education in South Africa, Transatlantic Science Education Cooperative, Stellenbosch University.
  + 2017 The People Side of Ecology, Social Science Methods Workshop, Dept. of Conservation Ecology and Entomology, Stellenbosch University.
  + 2016 Introduction to Phylogenetics Workshop, Forestry and Agricultural Biotechnology Institute, University of Pretoria.
  + 2016 Microsatellite Workshop, Forestry and Agricultural Biotechnology Institute, University of Pretoria.

## Digital Media Production 

### Data Visualization

  + [Tacoma schools, urban heat and trees](https://storymaps.arcgis.com/stories/0b8e2570da4a47d3a6ffb0907b738cea), (ArcGIS storymap).
  + [*Phytophthora* communities in eastern Cascade waterways](https://storymaps.arcgis.com/stories/af79904ceee04d019c8db5699819aaea), (ArcGIS storymap).
  + [Western Redcedar Dieback Map - Community Scientists (daily update)](https://public.tableau.com/app/profile/joey.hulbert/viz/ChampionObservers-dailyupdate/CommunityScientists), (Tableau Public).
  + [Western Redcedar Dieback Map - Preliminary Analysis (daily update)](https://public.tableau.com/app/profile/joey.hulbert/viz/WesternRedcedarDiebackMapAnalysis-dailyupdate/OverallSymptoms), (Tableau Public).


### YouTube Channels

  + [WSU Invasive Project - USDA APHIS Project # 5.0595](https://www.youtube.com/channel/UC8NuFF3nLpTwEvOSAy_I8LQ)
  + [WSU Ravenholt Urban Forest Health Lab](https://www.youtube.com/channel/UC8NuFF3nLpTwEvOSAy_I8LQ)

### YouTube Playlists
  + [Forest Health Watch](https://www.youtube.com/playlist?list=PLThL8bVy43vHk-Mf5a6jPa8qWY_Sd-hx1)

### Video Production

  + 2021 Western Redcedar Dieback Research and Community Science at Washington State University. [YouTube](https://youtu.be/mePe0T5m3oY).
  + 2021 Western Redcedar Dieback Map - Adding Observations to iNaturalist. [YouTube](https://www.youtube.com/watch?v=nh1Ye3pDONw).
  + 2020 Forest Health Watch - Puyallup High School Introduction. [YouTube](https://www.youtube.com/watch?v=cRrT1ix7XNE).
  + 2017 A year of empowering young minds. [YouTube](https://youtu.be/PKSI1sxHiEc).
  + 2016 Engage Kayamandi youth in Cape Citizen Science with Vision Afrika. [Experiment.com]( https://experiment.com/projects/engage-kayamandi-youth-in-cape-citizen-science-with-vision-afrika).
  + 2016 Release your inner scientist (website header). [YouTube](https://youtu.be/X-tXBPpDxWs).
  + 2015 Discovering plant destroyers in South Africa with citizen science. [Experiment.com](https://experiment.com/projects/discovering-plant-destroyers-in-south-africa-with-citizen-science).

### Podcast Production

  + 2017 [_Dylan_](https://archive.org/details/DylanE1), Cape Citizen Science.
  + 2015 _Behind the Research_, Oregon State University, College of Forestry.
  + 2012-2014 _Inspiration Dissemination_, Oregon State University, 88.7fm KBVR.

### Web Development

  + 2023- WSU Ravenholt Urban Forest Health Lab, Wordpress (https://treehealth.wsu.edu/)
  + 2023- WSU Invasive Species, Wordpress (https://extension.wsu.edu/invasive-species/)
  + 2020- Ornamental Plant Pathology, Wordpress (https://ppo.puyallup.wsu.edu/).
  + 2020- PNW Citizen Science, Github Pages (https://pnwcitsci.org/).
  + 2019- Forest Health Citizen Science Community, Github Pages (https://fhcs.page/).
  + 2018- R Workshop Series, html & R Markdown (https://jmhulbert.github.io/r/).
  + 2015- Cape Citizen Science, Wordpress (https://citsci.co.za).
  + 2015-2016 Personal website, Drupal (https://jmhulbert.me).
  + 2013-2014 Inspiration Dissemination, Drupal (oregonstate.edu/inspire).
  + 2013-2014 Botany and Plant Pathology Graduate Student Association, Drupal (https://gsa.bpp.oregonstate.edu).
  + 2013-2014 Western Forestry Graduate Research Symposium, Drupal (gradsymp.forestry.oregonstate.edu).
  + 2013-2014 Forest Graduate Undergraduate Mentorship Program, Drupal (gump.forestry.oregonstate.edu).

## Selected Popular Writing

  + Dewitz F, Hulbert JM. 2024 [Ten Priority Schools for Tree Planting in Tacoma](https://tacomatreefoundation.org/blog/ten-priority-shools-need-trees), Tacoma Tree Foundation Blog.
  + Hulbert JM. 2023 [Healthy maples, healthy communities](https://tacomatreefoundation.org/blog/healthy-maples-and-communities), Tacoma Tree Foundation Blog.
  + Hulbert JM. 2023. [Maple health watch - community scientists needed](https://foreststewardshipnotes.wordpress.com/2023/06/07/maple-health-watch-community-scientists-needed/), Forest Stewardship Notes, Washington Department of Natural Resources.
  + Zobrist K, Shults P, Hulbert JM. 2022. Focus on: emerald ash borer, WSU Puget Sound Extension Forestry Fall E-Newsletter.
  + Zobrist K, Shults P, Hulbert JM. 2022. [Washington residents should anticipate impacts from emerald ash borer ](https://foreststewardshipnotes.wordpress.com/2022/10/03/washington-residents-should-anticipate-impacts-from-emerald-ash-borer/), Forest Stewardship Notes, Washington Department of Natural Resources.
  + Hulbert JM. [Community scientists needed for western redcedar dieback research](https://www.mtnativeplants.org/wp-content/uploads/2021/10/Kelseya-v-34-4.pdf). Kelseya, Montana Native Plant Society, Volume 34, Issue 4, Summer 2021.
  + Hulbert JM. [Forest Health Watch – Opportunities to contribute to research and strengthen our biosecurity](https://online.flippingbook.com/view/868811809/22-23/). PNW ISA Trees, Spring Issue 2021.
  + Hulbert JM. [Pacific Northwest Forest Bio-Surveillance Training Available](https://foreststewardshipnotes.wordpress.com/2021/06/03/pacific-northwest-forest-bio-surveillance-training-available/), DNR & WSU Forest Stewardship Notes.
  + Hulbert JM 2021. [Community science and the dieback of western redcedar](http://www.b-e-f.org/wp-content/uploads/2021/02/BEF_Watersheds_newsletter242102_2.pdf), treeline, Bonneville Environmental Foundation, Watersheds Program. 
  + Hulbert JM 2020. [Forest Heatlh Watch - a new community science initiative in the Northwest](https://foreststewardshipnotes.wordpress.com/2020/10/01/forest-health-watch-a-new-community-science-initiative-in-the-northwest/), Forest Stewardship Notes, Washington Department of Natural Resources. 
  + Hulbert JM 2020. [You can contribute to western redcedar dieback research](https://sflonews.wordpress.com/2020/12/08/you-can-contribute-to-western-redcedar-dieback-research/), Small Forest Landowner News. 
  + Hulbert JM, Roets F. 2017\. Citizen science: how ordinary people can guard Cape Town's biodiversity, The Conversation-Africa.
  + Hulbert JM. 2017\. Pathogen Hunters: citizen scientists track plant diseases to save species, The Conversation-Africa.
  + Hulbert JM. 2017\. Two species of plant killing genus _Phytophthora_ found in a Western Cape garden, Veld & Flora Vol 103(1).
  + Hulbert JM. 2017\. Citizen Science, Supernova: the magazine for curious kids Vol 6.1.
  + Hulbert JM. 2016\. Citizen driven science: the citizen science movement in South Africa, Quest Magazine, Vol 12 (2).
  + Hulbert JM. 2016\. Plant Destroyers, Supernova: the magazine for curious kids, Vol 5.6.
  + Hulbert JM. 2016\. Super Fungi, Supernova: the magazine for curious kids, Vol 5.5.
  + Hulbert JM. 2016\. Citizen science: research experience for all, Veld & Flora, Vol 102(2).
  + Hulbert JM. 2016\. Recycled pathogens: avoiding accidental infection through awareness, Agrikultuur Magazine, Vol 34.
  + Hulbert JM. 2015\. Microbes, Supernova: the magazine for curious kids, Vol 5.3.
  + Hulbert JM. 2015\. Citizen engagement in research to protect fynbos—and forests, SA Forestry.
  + Hulbert JM. Navarro S. 2011\. Effective collaboration slows the spread of Sudden Oak Death in Oregon, Western Forester, Vol 56(3).



## Selected Media Coverage

### Articles

  + Angela Sams. 2024 [WSU partners with local community colleges to enhance urban forests](https://news.cahnrs.wsu.edu/article/wsu-partners-with-local-community-colleges-to-enhance-urban-forests/), WSU CAHNRS News. 
  + Simone Carter. 2024. [These 10 Tacoma schools could benefit the most from planting more trees, study shows](https://www.thenewstribune.com/news/local/article287501240.html), Tacoma News Tribune.
  + Craig Salor. 2024. [Tacoma gets $1.3 million to plant more trees in effort to protect kids, cool the city](https://www.thenewstribune.com/news/local/article286055601.html), Tacoma News Tribune.
  + Wenda Reed. 2023. [High and dry for a NW icon?](https://www.magcloud.com/webviewer/2562319), Washington State Magazine, Fall 2023.
  + Seth Truscott. 2023. [WSU sentinel plantings to guard against invasive pests, diseases at Washington ports](https://news.cahnrs.wsu.edu/article/wsu-sentinel-plantings-to-guard-against-invasive-pests-diseases-at-washington-ports/), WSU CAHNRS News
  + Joe Roberts. 2023. [Engaging the curious: WSU Extension educates and empowers citizen scientists](https://news.cahnrs.wsu.edu/article/engaging-the-curious-wsu-extension-educates-and-empowers-citizen-scientists/), WSU CAHNRS News
  + WSU, 2022. [Climate Science on Tap explores urban forests with WSU researcher](https://news.wsu.edu/announcements/climate-science-on-tap-explores-urban-forests-with-wsu-researcher/), WSU Insider
   + Sage Van Wing, 2022. [Western Redcedar trees in the Pacific Northwest are struggling](https://www.opb.org/article/2022/09/06/western-redcedar-trees-are-struggling/), Oregon Public Broadcasting, Think Out Loud.
  + Nicholas Turner. 2022. [Has this iconic Northwest tree reached a tipping point?](https://www.seattletimes.com/seattle-news/environment/has-this-iconic-northwest-tree-reached-a-tipping-point/), Seattle Times.
  + Pacific Education Institute. 2022. [Puget Sound teachers branch out with PEI's urban forestry storylines](https://www.climetime.org/puget-sound-teachers-branch-out-with-peis-urban-forestry-storylines/), online article.   + Anna Marie Pizzariello, Education Outreach Report Part 1, The Real Dirt, Master Gardener Foundation of Lewis County Newsletter.
  + Nathan Gilles. 2022. [Pac NW's 'trees of live' are dying. Now we know why](https://columbiainsight.org/pac-nws-trees-of-life-are-dying-now-we-know-why/), Columbia Insight, Online Article.
  + Craig Sailor. 2022. [Another tree disease has appeared in Pierce County, and this one can injure people, too](https://www.thenewstribune.com/news/local/article263269698.html?ac_cid=DM671103&ac_bid=446512792), The News Tribune, Tacoma Washington. Newspaper article. 
  + Pacific Education Institute. 2022. [PEI's Urban Forestry SOLS inspire PSESD teachers to explore forests with students](https://www.climetime.org/peis-urban-forestry-sols-inspire-psesd-teachers-to-explore-forests-with-students/), online article. 
  + Truscott S. 2022. [Tacoma tree planting helps young scientists learn how redcedar can survive changing climates](https://news.wsu.edu/news/2022/03/16/tacoma-tree-planting-helps-young-scientists-learn-how-redcedars-can-survive-changing-climate/), College of Agriculture, Human and Natural Resource Science, Washington State University. Online Article.
  + Wheeler H. 2021. [Takeaways from Forest Health Watch](https://www.issaquahalps.org/articles/2021/11/19/takeaways-from-forest-health-watch), Issaquah Alps Trail Club Newsletter.
  + Editor. 2021.[Using iNaturalist to track redcedar dieback](https://wnpskoma.org/wp-content/uploads/2021/04/Spring-2021.pdf). Koma Kushan Chapter WNPS Newsletter. 
  + Truscott S. 2021 [WSU researcher engages communities in tree health research with Forest Health Watch](https://news.cahnrs.wsu.edu/wsu-researcher-engages-communities-in-tree-health-research-with-forest-health-watch/), College of Agricultural, Human and Natural Resource Science, Washington State University, online article.
  + Truscott S. 2021 [WSU co-organizes first annual Pacific Northwest Citizen and Community Science Summit](https://news.cahnrs.wsu.edu/wsu-co-organizes-first-annual-pacific-northwest-citizen-and-community-science-summit/), College of Agricultural, Human and Natural Resource Science, Washington State University, online article.
  + Editor. 2021. [Comox Valley Nature lecture discusses western redcedar tree health](https://www.comoxvalleyrecord.com/community/comox-valley-nature-lecture-discusses-western-redcedar-dieback/), Comox Valley Record, newspaper.
  + Kempe Y. 2021. [An iconic tree is dying off in Whatcom — what’s causing it and how can you help save it?](https://www.bellinghamherald.com/news/local/article253989778.html#storylink=mainstage_lead), Bellingham Herald, Bellingham.
  + Extoque R. 2021. [The Unlikely Partnership Supporting South Seattle Youth Through Forest Science](https://southseattleemerald.com/2021/09/04/the-unlikely-partnership-supporting-south-seattle-youth-through-forest-science/#more-74007), South Sound Emerald, Seattle, digital newspaper.
  + Dunne N. 2021\. Mapping Cedar Dieback, University of Washington, Arboretum Bulletin, Washington. 
  + Inghram I. 2021\. Citizen scientists study western redcedars, Anacortes newspaper, Washington. 
  +  Peterson C. 2021. Help needed to assist dying western redcedars. Hungry Horse News and Whitefish Pilot, Montana.
  + Truscott S. 2021\. Citizen scientists can help study, halt die-off of Pacific Northwest’s redcedars,College of Agricultural, Human and Natural Resource Science, Washington State University, online article. 
  + Media and Communication 2018\. Getting citizen science into South African classrooms, University of Stellenbosch, online article.
  + de Bruin L. 2018\. Be part of the Cape Town hypothesis test, University of Pretoria homepage, online article.
  + Duvenage E. 2017\. Jy kan PhD-student help met grondmonsters, Die Burger, newspaper article.
  + Burt B. 2017\. Citizen scientists around the world take to the woods in an effort to improve the health of forests, IUFRO Spotlight # 49, online article.
  + Duvenage E. 2017\. Citizen science crowdfunding project pays off, SciBraai, online article.
  + Brits E. 2016\. 'Publiek kan help om fynbos te red, Netwerk 24, newspaper article.
  + Heyl A. 2016\. Join the hunt for pathogens in the fynbos, UP News, online article.
  + Editor. 2016\. Science Project aims to boost fynbos conservation, Boland Gazette, Hermanus Times, newspaper article.
  + DeKlerk, R. 2016\. Identifying plant diseases at the southernmost point of Africa SanParks Times, magazine article.

### Radio Interviews

  + NPR KUOW 94.9fm Seattle Washington [Port of Tacoma investigates new weapon to counter alien invasions](https://www.kuow.org/stories/port-of-tacoma-investigates-new-weapon-to-counter-alien-invasions), John Ryan. June 15, 2023.
  + NPR KNKX 88.5 Tacoma Washington, Sooty bark disease vulnerability study, July 12, 2022.
  + KBCS 91.3 Bellevue Washington, [The Redlined Western Redcedar Study Project](https://www.kbcs.fm/2021/11/18/the-redlined-western-red-cedar-study-project/), November 18, 2021.
  + [treehugger podcast](https://www.treehuggerpod.com/), Forest health and climate change (in production)
  + [treehugger podcast](https://www.treehuggerpod.com/), Madrones! with Arbutus ARME, January, 2021.
  + Cherry Creek Media, Wenatchee Washington, March 12, 2021.
  + Middag op RSG, RSG 100-104FM, January 23, 2018.
  + Detour, Maties MFM 92.6FM, November 29, 2017.
  + Green Living, Radio Helderberg 93.6FM, February 23, 2017.
  + KLCC News, NPR KLCC 89.7, April 8, 2015.


## Science Community Service

  + 2023 Guest Editor, Special Issue, Frontiers in Ecology and Evolution, *The Role of Community and Industry Surveillance in Managing Invasive Species: a Review of Current Knowledge*
  + 2023- Technical Advisory Committee Member, The effectiveness of trees in mitigating stormwater runoff in Western Washington – Phase 2, Washington State Department of Ecology
  + 2021 Promotion Review, External Evaluation, Associate Professor of Practice
  + 2021 Workshop Participant, _Citizen science and its future role for monitoring nature and the environment_ (Joint University Initiative, United Kingdom)
  + 2021 Adhoc Reviewer, Oregon State University Extension (1 Extension Publication)
  + 2021 Adhoc Reviewer, Journal of Plant Pathology (1 Manuscript)
  + 2021 Adhoc Reviewer, African Journal of Marine Science (1 Manuscript)
  + 2020 Adhoc Reviewer, Urban Forests Urban Greening (1 Manuscript)
  + 2020 Adhoc Reviewer, Journal of Science Communication (1 Manuscript)
  + 2020 Adhoc Reviewer, Journal of Plant Pathology (1 Manuscript)
  + 2020 Adhoc Reviewer, Scientific Reports (1 Manuscript)
  + 2019 Adhoc Reviewer, African Journal of Marine Biology (1 Manuscript)
  + 2018 Adhoc Reviewer, Biological Invasions (1 Manuscript)
  + 2016 Adhoc Reviewer, IMAfungus (1 Manuscript)

## Research Positions

  + 2020 - 2023 Postdoctoral Research Associate, Washington State University, Dept. of Plant Pathology, Puyallup Research and Extension Center. Primary Supervisor: Gary Chastagner. 
  + 2015 - 2019 Graduate Student, University of Pretoria, Dept. of Plant and Soil Sciences, Pretoria, Gauteng, South Africa. Primary Supervisor: Mike Wingfield. Co-supervisors: Treena Burgess, Francois Roets.
  + 2016 - 2018 Affiliate Research Student, Stellenbosch University, Dept. of Conservation Ecology and Entomology, Stellenbosch, Western Cape Province, South Africa. Supervisor: Francois Roets.
  + 2012 - 2014 Graduate Research Assistant, Oregon State University, Dept. of Wood Science and Engineering, Corvallis, Oregon, USA. Supervisors: Everett Hansen, Jeff Morrell.
  + 2011 - 2012 Research Technician, Oregon State University, Dept. of Botany and Plant Pathology, Corvallis, Oregon, USA. Supervisors: Everett Hansen, Paul Resser, Wendy Sutton.
  + 2010 Field Technician, Oregon State University, Dept. of Forest Engineering, Resources and Management, Corvallis, Oregon, USA. Supervisors: Dave Shaw, Travis Woolley.
  + 2009 Forest Service STEP Field Technician, Joint project with U.C. Davis and Forest Service Sierra Nevada Research Center, Davis, California, USA. Supervisors: Seth Bigelow, Michael Papaik, Malcolm North.
  + 2008 Field Technician, Joint project with University of Idaho and Forest Service Rocky Mountain Research Station, Moscow, Idaho, USA. Supervisors: Andrew Hudak, Penny Morgan.
  + 2008 Volunteer Lab Technician, Forest Pathology Lab, Forest Service Rocky Mountain Research Station, Moscow, Idaho, USA. Supervisors: Ned Klopfenstein, Mee-Sook Kim.
  + 2007 - 2010 Research Technician, Washington State University, Dept. of Plant Pathology, Pullman, Washington, USA. Supervisor: Patricia Okubara.
  + 2004 Research Technician, Kansas State University, Dept. of Plant Pathology, Manhattan, Kansas, USA.

## References

_Primary Postdoc Mentor_
**Gary Chastagner**
Professor, Washington State University
Extension Specialist, WSU Research and Extension Center in Puyallup
chastag@wsu.edu

_Postdoc Mentor_
**Marianne Elliott**
Research Associate, Washington State University Research and Extension Center in Puyallup
melliott2@wsu.edu

_Puyallup Research and Extension Director_
**Todd Murray**
Director, WSU Research and Extension Center in Puyallup
Washington State University
tmurray@wsu.edu

_Primary PhD Supervisor_
**Mike J. Wingfield**
Advisor to the Executive, University of Pretoria
Past President, International Union of Forest Research Organizations
Founding Director, Forestry and Agricultural Biotechnology Institute
Professor, Department of Microbiology and Plant Pathology
University of Pretoria, Pretoria, South Africa 0002
mike.wingfield@up.ac.za

_PhD Co-Supervisor_
**Treena I. Burgess**
Research Director - Institutes, Murdoch University
Director, Centre of _Phytophthora_ Science and Management
Professor, Plant Biology
Murdoch University, Murdoch, Western Australia 6150
t.burgess@murdoch.edu.au

_PhD Co-Supervisor_
**Francois Roets** 
Assistant Professor, Dept. of Conservation Ecology and Entomology
Stellenbosch University, Stellenbosch, South Africa 7600
fr@sun.ac.za

_MSc Supervisor_
**Everett M. Hansen**
Professor Emeritus, Dept. of Botany and Plant Pathology
Oregon State University, Corvallis, Oregon, USA 97330
hansene@oregonstate.edu