---
title: "Joseph (Joey) Michael Hulbert"
date:
subtitle: "Ornamental Plant Pathology,\n\nPuyallup Research and Extension Center,
  \n\nWashington State University, \n\n2606 West Pioneer, Puyallup, WA, 98371-4998
  USA. \n\nhttps://jmhulbert.github.io \n\n1-541-908-5129 \n\nhulbe@wsu.edu\n"
output:
  pdf_document: default
  html_document: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Academic Appointments
<table>
<tbody>
<tr valign="top">
<td width="100">
2020-2022
</td>
<td width="892">
**USDA NIFA Postdoctoral Fellow**, Ornamental Plant Pathology, WSU Puyallup Research and Extension Center, Washington State University.
</td>
</tr>
</tbody>
</table>

## Education
<table>
<tbody>
<tr valign="top">
<td width="100">
2015-2020 (February)
</td>
<td width="892">
**PhD** Plant Pathology, Forestry and Agricultural Biotechnology Institute, Dept. of Plant & Soil Science, University of Pretoria, South Africa. Dissertation: _Phytophthora_ diversity in the Cape Floristic Region. Primary Supervisor: Mike Wingfield. Co-Supervisors: Treena Burgess, Francois Roets.
</td>
</tr>
<tr valign="top">
<td width="100">
2016-2019
</td>
<td width="892">
**Affiliate Research Student**, Dept. of Conservation Ecology & Entomology, Stellenbosch University, South Africa.
</td>
</tr>
<tr valign="top">
<td width="100">
2012-2014
</td>
<td width="892">
**Dual MSc** Dept. of Botany & Plant Pathology, Dept. of Wood Science & Engineering, Oregon State University. Thesis: Phytosanitation of Douglas-fir (_Pseudotsuga menziesii_) logs to mitigate the risk of artificially disseminating _Phytophthora ramorum_ within the global trade of timber. Advisers: Everett Hansen & Jeff Morrell.
</td>
</tr>
<tr valign="top">
<td width="100">
2006-2010
</td>
<td width="892">
**BSc** Dept. of Natural Resource Sciences, Washington State University. Undergraduate Thesis: Influence of climatic variables on forest growth in the Sierra Nevada Mountains.
</td>
</tr>
</tbody>
</table>


## Initiatives
<table>
<tbody>
<tr valign="top">
<td width="100">
2020-
</td>
<td width="892">
Program director, _Forest Health Watch_ ([https://foresthealth.org/](https://foresthealth.org/)), Washington State University, United States Department of Agriculture, National Institute of Food and Agriculture.
</td>
</tr>
<tr valign="top">
<td width="100">
2020-
</td>
<td width="892">
Organizer, _WSU Forestry Working Group_, Washington State University.
</td>
</tr>
<tr valign="top">
<td width="100">
2016-
</td>
<td width="892">
Project leader, _Cape Citizen Science_ ([https://citsci.co.za/](https://citsci.co.za/)), Forestry and Agricultural Biotechnology Institute, University of Pretoria, Stellenbosch University, DST-NRF Centre of Excellence in Tree Health Biotechnology.
</td>
</tr>
</tbody>
</table>

## Publications 
<table>
<tbody>
<tr valign="top">
<td width="100">
Peer reviewed
</td>
<td width="892">
7
</td>
</tr>
<tr valign="top">
<td width="100">
Not peer reviewed
</td>
<td width="892">
8
</td>
</tr>
<tr valign="top">
<td width="100">
In prep, review or revision
</td>
<td width="892">
5
</td>
</tr>