---
title: "JMH CV Visualized"
author: "Joey Hulbert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridisLite)
```


```{r fig.height=4, fig.width=8}
# Creating a data frame with the academic events in reversed order and original end dates
events <- data.frame(
  Event = c("Postdoctoral Research Associate",
            "USDA NIFA Postdoctoral Fellow", 
            "PhD Plant Pathology", 
            "Dual MSc Botany & Plant Pathology/Wood Science & Engineering", 
            "BSc Natural Resource Sciences"),
  Start = as.Date(c("2022-01-01", "2020-01-01", "2015-01-01", "2012-01-01", "2006-01-01")),
  End = as.Date(c("2024-12-31", "2021-12-31", "2019-12-31", "2014-12-31", "2009-12-31")),  # Original end dates
  EventNum = c(1,2,3,4,5)  # Reversed order
)
?viridis

events <- events %>% mutate(Color=viridis(5))

# Plotting the timeline using ggplot2
ggplot() +
  geom_segment(data = events, aes(x = Start, xend = End, y = EventNum, yend = EventNum,color=Color), size = 1) +
  geom_point(data = events, aes(x = Start, y = EventNum,fill=Color), size = 3, shape = 21) +
  geom_point(data = events, aes(x = End, y = EventNum,fill=Color), size = 3, shape = 21) +
  scale_x_date(breaks = seq(as.Date("2005-01-01"), as.Date("2025-12-31"), by = "5 years"), date_labels = "%Y") +
  scale_y_continuous(breaks = 1:5, labels = events$Event) +
  labs(title = "Joseph Hulbert's Academic Career", 
       x = "Year", y = "Appointment") +
  theme_bw() +
  guides(color=F,fill=F)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank())
```

```{r fig.height=4, fig.width=8}
# Assuming 'grouped_by_year' is your data frame similar to the one used in Python
# Replace 'grouped_by_year' with the actual name of your data frame
# The data frame should have columns: Year, Talk Type, and Count

data <-read.csv("./cv/data/PresentationList-AI-table.csv")

# Reshaping the data for ggplot
#data_long <- gather(data, key = "Audience", value = "Count", -Year)

# Creating the stacked bar plot
ggplot(data, aes(Year, fill = Audience)) +
  geom_histogram(binwidth=0.5) +
  scale_fill_viridis_d() +  # Viridis color scale
  scale_x_continuous(breaks=seq(2011,2023,by=1)) +
  theme_bw() +
  labs(title = "Presentations by Joseph Hulbert",
       x = "Year",
       y = "Number of Presentations",
       fill = "Audience") +
  theme(plot.title = element_text(hjust = 0.5),  # Centering the title
        legend.position = "right",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  annotate("text", x = 2011, y = 35, 
           label = paste("Total Presentations:", length(data$Title)), 
           hjust = 0, vjust = 0, size = 4)  # Annotation for total presentations

# Note: Adjust the x and y values in annotate() to position your text as needed
```

