---
title: "FABI Session 4 - Introduction to vegan"
subtitle: "Forestry and Agricultural Biotechnology Institute, University of Pretoria"
author: "Joey Hulbert"
date: "March 7, 2019"
output: html_document
---
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });
    });
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(knitr)
```

## Introduction

More information will be added soon

```{r eval=FALSE, include=FALSE}
## change abundance data to presence absence data.


understory <- read.csv('./data/Forest_understory_presence.csv')
names(understory)
response <- understory[-c(1:3)]
explanitory <- understory[c(1,2,3)]
#check the number of factors in the environment
rownames(understory)

Site_Name_Permanova <-adonis2(response ~ Site.Name,perm=9999,method="bray",by="margin",data=explanitory)
Permanova

Focal_Species_Permanova<-adonis2(response ~ Site.Name/Focal.Tree,perm=9999,method="bray",by="margin",data=explanitory)
Focal_Species_Permanova


sp2 <- specaccum(response, "random")
plot(sp2, ci.type="poly", col="blue", lwd=2, ci.lty=0, ci.col="lightblue")


distance <- metaMDS(response,distance="bray",trace=FALSE,trymax=100)

plot(distance,type="n")
points(distance,display="sites")
text(distance,display="species",cex=0.7,col="blue")
ordiellipse(distance,explanitory$Site.Name,kind="se", conf=0.95, lwd=2,draw = "polygon", col=1:4, border=1:4, alpha=63, label=FALSE)
Forests <-c("GrootvadersBos","Kleinbos","Woodville","Witelsbos")
legend(0.1,legend=Forests,col = 1:4, pt.bg = 1:4, bty = "n")
?legend()


```

