---
title: "FABI Session 2 - Introduction to ggplot2"
subtitle: "Forestry and Agricultural Biotechnology Institute, University of Pretoria"
author: "Joey Hulbert"
date: "February 21, 2019"
output: html_document
---
<script>
    $(document).ready(function() {
      $items = $('div#TOC li');
      $items.each(function(idx) {
        num_ul = $(this).parentsUntil('#TOC').length;
        $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
      });
    });
</script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(knitr)
```

## Introduction

More information will be added soon

```{r include=FALSE}
#Italics
#geom_text
#facet_wraps
```



```{r}
##Rwksp Session 2 - ggplot2###

##1. Load Packages####
library(tidyverse)

##2. Index Data####
Forest_data <-read.csv("Rwksp Forest Data.csv")

##3. Check & Adjust Data####
str(Forest_data)
names(Forest_data)
summary(Forest_data)
##4. Exploratory Plots####

#_a. Bar plot####
ggplot(data=Forest_data)+geom_bar(mapping=aes(x=Species)) +coord_flip()

#_b. Histogram for continuous data####
ggplot(data=Forest_data)+geom_bar(mapping=aes(x=Diameter))
ggplot(data=Forest_data)+geom_freqpoly(mapping=aes(x=Diameter,color=Species))

#_c. Short####
ggplot(Forest_data)+geom_bar(aes(x=Diameter))

#_c. Labels####

ggplot(data=Forest_data)+geom_freqpoly(mapping=aes(x=Diameter,color=Species))+labs(title="Southern Afrotemperate Forest Species Abundance",x="Diameter",y="Number of Trees")

##5. Subsetting####
Podo <- subset(Forest_data,Forest_data$Species=="Podocarups latifolius")

levels(Podo$Plot.ID)
Plot1 <-subset(Forest_data,Forest_data$Plot.ID=="bgb14b5429")

ggplot(Plot1,aes(Year,Diameter,color=Species,linetype=Species))+geom_smooth(method=lm)
#ggplot(Podo,aes(Year,Diameter))+geom_smooth(method=lm)

##6. Facet Wrapping####
Forest_data$Year <-as.factor(Forest_data$Year)
ggplot(Podo,aes(Year,Diameter,col=Bioregion))+geom_boxplot() +facet_wrap(~Aspect)
```

